
/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
DROP TABLE IF EXISTS `aes_passwords`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `aes_passwords` (
  `uid` int(10) unsigned NOT NULL DEFAULT '0',
  `pass` varchar(128) NOT NULL DEFAULT '',
  PRIMARY KEY (`uid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
/*!40101 SET character_set_client = @saved_cs_client */;

LOCK TABLES `aes_passwords` WRITE;
/*!40000 ALTER TABLE `aes_passwords` DISABLE KEYS */;
INSERT INTO `aes_passwords` VALUES (1,'PmgtJ+AYRUhzSKlTO47SMQ==');
INSERT INTO `aes_passwords` VALUES (9,'TfS46UoeDwLgk8ze4TjM4w==');
INSERT INTO `aes_passwords` VALUES (10,'rqH71QKOOE0UWsVdmSpO0w==');
INSERT INTO `aes_passwords` VALUES (12,'kYx1To/RakzJShsexvjBtA==');
INSERT INTO `aes_passwords` VALUES (13,'mraGMOQPmWNotGZCXJ0FmQ==');
INSERT INTO `aes_passwords` VALUES (15,'OVPqh2NxMmJMs6NUiKDoNw==');
INSERT INTO `aes_passwords` VALUES (16,'M+CinwkKIC+qtHn8SHZd9Q==');
INSERT INTO `aes_passwords` VALUES (33,'OVPqh2NxMmJMs6NUiKDoNw==');
INSERT INTO `aes_passwords` VALUES (70,'2lhOETkz8FOjj5dr4+IcxhXXQaII2RiJNGMn1kqaFYw=');
INSERT INTO `aes_passwords` VALUES (86,'q7F+nHZhPfJHj+bAEI9MXg==');
/*!40000 ALTER TABLE `aes_passwords` ENABLE KEYS */;
UNLOCK TABLES;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

