
/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
DROP TABLE IF EXISTS `block_custom`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `block_custom` (
  `bid` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT 'The block’s block.bid.',
  `body` longtext COMMENT 'Block contents.',
  `info` varchar(128) NOT NULL DEFAULT '' COMMENT 'Block description.',
  `format` varchar(255) DEFAULT NULL COMMENT 'The filter_format.format of the block body.',
  PRIMARY KEY (`bid`),
  UNIQUE KEY `info` (`info`)
) ENGINE=InnoDB AUTO_INCREMENT=26 DEFAULT CHARSET=utf8 COMMENT='Stores contents of custom-made blocks.';
/*!40101 SET character_set_client = @saved_cs_client */;

LOCK TABLES `block_custom` WRITE;
/*!40000 ALTER TABLE `block_custom` DISABLE KEYS */;
INSERT INTO `block_custom` VALUES (1,'<p><a href=\"http://www.achievingthedream.org/news/diesel_program_nurtures_partnership_with_yancey_brothers\" target=\"_blank\"><img alt=\"\" class=\"image-inline_photo_float_left\" src=\"http://www.achievingthedream.org/sites/default/files/styles/node-level_attached_image/public/images/Athens%20Tech.jpg\" style=\"height: 132px; width: 150px; float: left;\" title=\"\" /></a><strong>Four Recent Grads Gain Employment Through College Partnership</strong></p><p>Four recent graduates of Athens Technical College&rsquo;s Diesel Equipment Technology program are now working at Caterpillar equipment dealer Yancey Brothers Co.&rsquo;s Dacula facility thanks to a promising new partnership between Yancey Brothers and the college.</p><p><a href=\"http://www.achievingthedream.org/news/diesel_program_nurtures_partnership_with_yancey_brothers\">Read the full story</a>.</p>','homepage spotlight item','full_html');
INSERT INTO `block_custom` VALUES (2,'<!--\r\n<a href=\"#\" id=\"donate-button\">Donate</a>\r\n-->','donate button','full_html');
INSERT INTO `block_custom` VALUES (3,'<h3>Achieving the Dream, Inc.</h3><p>8455 Colesville Road, Suite 900<br />Silver Spring, Maryland 20910<br />Phone (240) 450-0075<br />Fax (240) 450-0076<br /><a href=\"/contact\">Email us</a><br /><a href=\"/about/directions\">Directions</a></p><p><a href=\"https://www.facebook.com/achievingthedream\" target=\"_blank\"><img alt=\"Facebook\" src=\"/sites/default/files/images/fb_icon.jpg\" width=\"24\" /></a>&nbsp;<a href=\"http://www.twitter.com/achievethedream\" target=\"_blank\"><img alt=\"Twitter\" src=\"/sites/default/files/images/tw_icon_transparent.png\" width=\"24\" /></a></p><p>&nbsp;</p><p>&nbsp;</p><p class=\"more-link\">&copy; 2012, Achieving the Dream<br />Site by <a href=\"http://www.grandjunctiondesign.com\" target=\"_blank\">Grand Junction Design</a></p>','footer contact info','filtered_html');
INSERT INTO `block_custom` VALUES (4,'<h3>Learn More</h3><ul><li><a href=\"/resources/knowledge_center\">Knowledge Center</a></li><li><a href=\"/resources/newsletter/achieving_success\">Achieving Success (Policy Newsletter)</a></li><li><a href=\"/resources/newsletter/data_notes\">Data Notes (Data Newsletter)</a></li><li><a href=\"/resources/cutting_edge_series\">Cutting Edge Series</a></li><li><a href=\"/resources/principles_practices\">Principles and Practices of Student Success</a></li></ul><h3>Tools</h3><ul><li><a href=\"http://www.achievingthedreammembers.org/members/datatools.html\">Data Tools</a></li><li><a href=\"/search_knowledge_center?field_resource_type_tid%5B%5D=28\">Self-Assessments</a></li><li><a href=\"/annualreport\">Annual Report Guidelines</a></li><li><a href=\"/implementationproposal\">Implementation Proposal Guidelines</a></li></ul>','footer links 1','filtered_html');
INSERT INTO `block_custom` VALUES (5,'<h3>About</h3><ul><li><a href=\"/about\">Overview</a></li><li><a href=\"/about/history\">History</a></li><li><a href=\"/approach\">Approach</a></li><li><a href=\"/approach/institutional_change\">Institutional Change</a></li><li><a href=\"/approach/policy_change_0\">Policy Change</a></li><li><a href=\"/approach/knowledge_development\">Knowledge Development</a></li><li><a href=\"/approach/public_engagement\">Public Engagement</a></li><li><a href=\"/news/in_the_news\">In the News</a></li><li><a href=\"/form_990\">Form 990</a></li></ul><h3>Results</h3><ul><li><a href=\"/results/colleges\">Colleges</a></li><li><a href=\"/results/policy\">Policy</a></li></ul>','footer links 2','filtered_html');
INSERT INTO `block_custom` VALUES (6,'<h3>Get to Know Us</h3><ul><li><a href=\"/network/board\">Board of Directors</a></li><li><a href=\"/network/staff\">Staff</a></li><li><a href=\"/map/colleges\">Colleges</a></li><li><a href=\"/about/network/state_policy_teams\">States</a></li><li><a href=\"/network/coaches\">Coaches</a></li><li><a href=\"/network/advisors\">Advisors</a></li><li><a href=\"/network/partners\">Founding Partners</a></li><li><a href=\"/about/network/investors\">Investors</a></li></ul><h3>Get Involved</h3><ul><li><a href=\"/get_involved/events\">Attend</a></li><li><a href=\"/get_involved/prospective_colleges\">Join</a></li><li><a href=\"/get_involved/jobs\">Work</a></li><li><a href=\"/DREAM2013\">DREAM 2013</a></li><li><a href=\"http://www.achievingthedream.org/join/2013_cohort_RFP\">2013 Cohort RFP</a></li></ul>','footer links 3','filtered_html');
INSERT INTO `block_custom` VALUES (8,'<p> </p>','Empty block','full_html');
INSERT INTO `block_custom` VALUES (9,'<p><img alt=\"\" src=\"/sites/default/files/styles/inline_chart_float_left/public/images/atd_model.png\" id=\"chart-atd-model\" class=\"inline_chart_float_left\" />Achieving the Dream community colleges commit to our Student-Centered Model of Institutional Improvement. Based on four principles, the model frames the overall work of helping more students, particularly low- income students and students of color, stay in school and earn a college certificate or degree.</p><p>Each college approaches the work differently, but Achieving the Dream&rsquo;s five-step process provides practical guidelines for keeping the focus where it belongs and building momentum over time. Throughout the process, Achieving the Dream coaches offer customized support and help each college&rsquo;s core team implement data-informed programs and policies that build long-term, institution-wide commitment to student success.</p>\r\n<div class=\"clear\">&nbsp;</div>','ATD Model','full_html');
INSERT INTO `block_custom` VALUES (10,'<p>Leader Colleges are demonstrating the power of the Achieving the Dream Student-Centered Model of Institutional Improvement. They show us it is possible to raise persistence and graduation rates, close achievement gaps, and change lives. Leader Colleges embody the ultimate goal of Achieving the Dream, and as such, serve as mentors within our community of learners.</p><p>To be eligible for Leader College distinction, colleges must show three or more years of improvement on one or more of these five measures:</p><ul><li>Course completion</li><li>Advancement from developmental to credit-bearing courses</li><li>Completion of college-level math and English courses</li><li>Term-to-term and year-to-year retention</li><li>Completion of certificates or degrees</li></ul>','Leader Colleges for profiles','filtered_html');
INSERT INTO `block_custom` VALUES (11,'<p><strong>Achieving the Dream, Inc.</strong><br />8455 Colesville Road, Suite 900<br />Silver Spring, Maryland 20910<br />Phone (240) 450-0075<br />Fax (240) 450-0076<br />Email: <a href=\"mailto:info@achievingthedream.org\">info@achievingthedream.org</a><br /><a href=\"/about/directions\">Directions</a></p><!--\r\n<p><strong>Scheduling Requests</strong>: Contact Fiona Thomas, Executive Assistant to the President and CEO at <a href=\"mailto:FThomas@AchievingtheDream.org\">FThomas@AchievingtheDream.org</a>.</p><p><strong>Media Inquiries</strong>: Contact Katie Loovis, Chief Operating Officer, at (919) 696-0781 (cell) or <a href=\"mailto:KLoovis@AchievingtheDream.org\">KLoovis@AchievingtheDream.org</a>.</p><p><strong>General Inquiries</strong>: Contact Achieving the Dream, Inc. staff at <a href=\"mailto:Info@AchievingtheDream.org\">Info@AchievingtheDream.org</a>, which is monitored daily by our Administrative Assistant Jazmin Lopez, or use the form below.</p>\r\n-->','contact form (top)','full_html');
INSERT INTO `block_custom` VALUES (12,'<p>Filter by Status:</p><ul><li><a href=\"/map/colleges/leader_colleges\">Leader College</a></li><li><a href=\"/map/colleges\">Participating Institution</a></li><li><a href=\"/map/colleges/former_institutions\">Former Institution</a></li></ul>','manual filters for college status','filtered_html');
INSERT INTO `block_custom` VALUES (13,'<form action=\"/resources/knowledge_center\" method=\"post\" id=\"search-block-form\" accept-charset=\"UTF-8\"><div><div class=\"container-inline\">\r\n      <h2 class=\"element-invisible\">Search form</h2>\r\n    <div class=\"form-item form-type-textfield form-item-search-block-form\">\r\n  <label class=\"element-invisible\" for=\"edit-search-block-form--2\">Search </label>\r\n <input title=\"Enter the terms you wish to search for.\" type=\"text\" id=\"edit-search-block-form--2\" name=\"search_block_form\" value=\"\" size=\"40\" maxlength=\"128\" class=\"form-text\">\r\n</div>\r\n<div class=\"form-actions form-wrapper\" id=\"edit-actions\"><input type=\"submit\" id=\"edit-submit--2\" name=\"op\" value=\"Search\" class=\"form-submit\"></div><input type=\"hidden\" name=\"form_build_id\" value=\"form-L6fldPAopE93lLP6HV4013-8Bm75fFLVkDB0UpgJ0Dg\">\r\n<input type=\"hidden\" name=\"form_token\" value=\"9gX2tGX68e3CAHBydn9bg5CW4T8EKMRsI6fqrfjriQI\">\r\n<input type=\"hidden\" name=\"form_id\" value=\"search_block_form\">\r\n</div>\r\n</div></form>','search form (extra for Knowledge Center)','full_html');
INSERT INTO `block_custom` VALUES (14,'<p>&nbsp;</p><p>Video produced by <a href=\"http://www.fireflyinteractivemedia.com\" target=\"_blank\">Firefly Interactive Media</a></p>','firefly media','filtered_html');
INSERT INTO `block_custom` VALUES (15,'<p>Leader Colleges have demonstrated commitment to and made progress on the four principles of Achieving the Dream:</p><ul><li>committed leadership</li><li>use of evidence to improve programs and services</li><li>broad engagement, and</li><li>systemic institutional improvement.</li></ul><p>They have also shown three years of sustained student success improvement. We expect these colleges to serve as mentors within the Achieving the Dream community of learners, as well as advocates for the principles of Achieving the Dream.</p><p><a href=\"http://www.achievingthedream.org/get_involved/leader_colleges\">Learn more</a>.</p>','leader college requirements (for leader college landing page)','filtered_html');
INSERT INTO `block_custom` VALUES (16,'<!-- AddThis Button BEGIN -->\r\n<div class=\"addthis_toolbox addthis_default_style \">\r\n<a class=\"addthis_button_preferred_1\"></a>\r\n<a class=\"addthis_button_preferred_2\"></a>\r\n<a class=\"addthis_button_preferred_3\"></a>\r\n<a class=\"addthis_button_preferred_4\"></a>\r\n<a class=\"addthis_button_compact\"></a>\r\n<a class=\"addthis_counter addthis_bubble_style\"></a>\r\n</div>\r\n<script type=\"text/javascript\" src=\"http://s7.addthis.com/js/250/addthis_widget.js#pubid=ra-4f2c0a9a12a7607a\"></script>\r\n<!-- AddThis Button END -->','AddThis','full_html');
INSERT INTO `block_custom` VALUES (17,'<ul><li><a href=\"http://nonprofitmarketingblog.com\" target=\"_blank\">Katya&#39;s Nonprofit Marketing Blog</a></li><li><a href=\"http://thp.org/blog\" target=\"_blank\">Hunger Project Blog</a></li><li><a href=\"http://blog.worldvision.org/\" target=\"_blank\">World Vision Blog</a></li><li><a href=\"http://blog.feedingamerica.org/\" target=\"_blank\">Feeding America</a></li><li>etc.</li></ul>','Blogroll','filtered_html');
INSERT INTO `block_custom` VALUES (18,'<script charset=\"utf-8\" src=\"http://widgets.twimg.com/j/2/widget.js\"></script><script>\r\nnew TWTR.Widget({\r\n  version: 2,\r\n  type: \'search\',\r\n  search: \'#dream2013\',\r\n  interval: 30000,\r\n  title: \'The buzz about\',\r\n  subject: \'#DREAM2013\',\r\n  width: 170,\r\n  height: 400,\r\n  theme: {\r\n    shell: {\r\n      background: \'#00a29a\',\r\n      color: \'#ffffff\'\r\n    },\r\n    tweets: {\r\n      background: \'#ffffff\',\r\n      color: \'#444444\',\r\n      links: \'#00a29a\'\r\n    }\r\n  },\r\n  features: {\r\n    scrollbar: true,\r\n    loop: false,\r\n    live: true,\r\n    behavior: \'all\'\r\n  }\r\n}).render().start();\r\n</script>','twitter search dream2013','full_html');
INSERT INTO `block_custom` VALUES (19,'<ul><li><a href=\"/retreat/2012_spring/purpose_desired_outcomes\">Purpose and Desired Outcomes</a></li><li><a href=\"/retreat\">Handouts and Presentations</a></li><li><a href=\"/retreat/2012_spring/contact_lists\">Contact Lists</a></li><li><a href=\"/sites/default/files/2012_Spring_Retreat_Agenda.pdf\">Agenda (PDF)</a></li><li><a href=\"/sites/default/files/2012_Spring_Retreat_Evaluation_Summary.pdf\">Evaluation Summary (PDF)</a></li><li><a href=\"/2012FallCoachRetreat\">2012 Fall Retreat Materials</a></li></ul>','2012 Spring Retreat Subnav','filtered_html');
INSERT INTO `block_custom` VALUES (20,'<ul><li><a href=\"/PRESS_grant_resources/home\">Home-Walmart Grant Recipient Resources</a></li><li><a href=\"/sites/default/files/PRESS_Kickoff_Agenda_0.pdf\">Agenda (PDF)</a></li><li><a href=\"/sites/default/files/PRESS_for_Completion_Participant_List.pdf\">Contact List (PDF)</a></li><li><a href=\"/sites/default/files/PRESS_for_Completion_Important_Dates.pdf\">Important Dates (PDF)</a></li><li><a href=\"/sites/default/files/PRESS_for_Completion_Deliverable_Timeline_JUNE%202012.pdf\">Deliverable Timeline (PDF)</a></li><li><a href=\"/sites/default/files/PRESS_for_Completion_College_Work%20Plan_FINAL.doc\">Grant Recipient Timeline (DOC) </a></li><li><a href=\"/sites/default/files/cdat_loss%26momentum_r101.pdf\">CBD Loss and Momentum Handout (PDF)</a></li></ul><p><a href=\"http://www.achievingthedream.org/initiatives/PRESS\">Additional Information on the Walmart PRESS for Completion Grant Program </a></p><p>&nbsp;</p>','2012 Walmart Grant Recipient Resources (hidden) Sidebar Menu','filtered_html');
INSERT INTO `block_custom` VALUES (22,'<ul><li><a href=\"http://www.achievingthedream.org/sites/default/files/2012_Kickoff_AGENDA_FINAL.pdf\">Kickoff Institute Agenda (PDF)</a></li><li><a href=\"http://www.achievingthedream.org/sites/default/files/Achieving_the_Dream_2012_Cohort.pdf\">Achieving the Dream 2012 Cohort (PDF) </a></li><li><a href=\"http://www.achievingthedream.org/sites/default/files/2012_Coach_Assignments.pdf\">2012 Coach Assignments (PDF)</a></li><li><a href=\"http://www.achievingthedream.org/sites/default/files/Founding_Partners_and_Consultants.pdf\">Founding Partners and Consultants (PDF)</a></li><li><a href=\"http://www.achievingthedream.org/sites/default/files/Leadership_and_Data_Coach_Contact_2012.pdf\">Leadership and Data&nbsp;Coaches&#39; Contact Information (PDF) </a></li><li><a href=\"http://www.achievingthedream.org/sites/default/files/Particpants_2012.pdf\">Participants List (PDF)</a></li><li><a href=\"http://www.achievingthedream.org/sites/default/files/Speaker_Bios.pdf\">Speaker Bios (PDF)</a></li><li><a href=\"http://www.achievingthedream.org/sites/default/files/Special_Guests.pdf\">Special Guests (PDF)</a></li></ul>','2012 Kickoff Institute','filtered_html');
INSERT INTO `block_custom` VALUES (23,'The Knowledge Center is a searchable database containing videos, articles, and reports from Achieving the Dream Founding Partners, Partner Organizations, and other experts entrenched in the work of community colleges and student success. These aids shall serve as support to Achieving the Dream Institutions throughout the process of institutional reform, and aid in creating a culture of continuous improvement. You can search by step in the five step process or filter by topic, type, or keyword.','knowledge center intro text','filtered_html');
INSERT INTO `block_custom` VALUES (24,'<div class=\"clearfix\" id=\"dream2013-banner\"><img a=\"\" alt=\" image=\" by=\"\" derived=\" \" flickr=\"\" from=\"\" height=\"100\" palm=\"\" photo=\"\" src=\"/sites/all/themes/ATD/images/dream-banner_palms.jpg\" title=\"Image derived from \'Palm Tree Storm,\' a photo by flickr user HidingInABunker\" tree=\"\" user=\"\" width=\"720\" /><h1 class=\"hidden\" id=\"dream2013-title\">DREAM 2013: Equity &amp; Excellence</h1><p id=\"dream2013-blurb\"><strong>Achieving the Dream&#39;s<br />Annual Meeting on Student Success</strong><br />February 5-8, 2013<br />Hilton Anaheim, Anaheim, California</p></div>','DREAM2013 Banner','full_html');
INSERT INTO `block_custom` VALUES (25,'<ul><li><a href=\"http://achievingthedream.org/sites/default/files/2012FallRetreatAgenda.pdf\" target=\"_blank\">Agenda (PDF)</a></li><li><a href=\"/2012FallCoachRetreat\">Handouts and Presentations</a></li><li><a href=\"http://achievingthedream.org/sites/default/files/FinancePresentation_PerDiemAndInsurance.pdf\">Finance Presentation&nbsp;for Data Coaches</a>&nbsp;(Per Diem &amp; Insurance)</li><li><a href=\"http://achievingthedream.org/sites/default/files/PTK_C4AdminGuide.pdf\">PTK C4 Administrators Guide</a></li><li><a href=\"/retreat\">2012 Spring Retreat Materials</a></li></ul>','2012 Fall Retreat Sidebar','filtered_html');
/*!40000 ALTER TABLE `block_custom` ENABLE KEYS */;
UNLOCK TABLES;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

