
/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
DROP TABLE IF EXISTS `block`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `block` (
  `bid` int(11) NOT NULL AUTO_INCREMENT COMMENT 'Primary Key: Unique block ID.',
  `module` varchar(64) NOT NULL DEFAULT '' COMMENT 'The module from which the block originates; for example, ’user’ for the Who’s Online block, and ’block’ for any custom blocks.',
  `delta` varchar(32) NOT NULL DEFAULT '0' COMMENT 'Unique ID for block within a module.',
  `theme` varchar(64) NOT NULL DEFAULT '' COMMENT 'The theme under which the block settings apply.',
  `status` tinyint(4) NOT NULL DEFAULT '0' COMMENT 'Block enabled status. (1 = enabled, 0 = disabled)',
  `weight` int(11) NOT NULL DEFAULT '0' COMMENT 'Block weight within region.',
  `region` varchar(64) NOT NULL DEFAULT '' COMMENT 'Theme region within which the block is set.',
  `custom` tinyint(4) NOT NULL DEFAULT '0' COMMENT 'Flag to indicate how users may control visibility of the block. (0 = Users cannot control, 1 = On by default, but can be hidden, 2 = Hidden by default, but can be shown)',
  `visibility` tinyint(4) NOT NULL DEFAULT '0' COMMENT 'Flag to indicate how to show blocks on pages. (0 = Show on all pages except listed pages, 1 = Show only on listed pages, 2 = Use custom PHP code to determine visibility)',
  `pages` text NOT NULL COMMENT 'Contents of the "Pages" block; contains either a list of paths on which to include/exclude the block or PHP code, depending on "visibility" setting.',
  `title` varchar(64) NOT NULL DEFAULT '' COMMENT 'Custom title for the block. (Empty string will use block default title, <none> will remove the title, text will cause block to use specified title.)',
  `cache` tinyint(4) NOT NULL DEFAULT '1' COMMENT 'Binary flag to indicate block cache mode. (-2: Custom cache, -1: Do not cache, 1: Cache per role, 2: Cache per user, 4: Cache per page, 8: Block cache global) See DRUPAL_CACHE_* constants in ../includes/common.inc for more detailed information.',
  PRIMARY KEY (`bid`),
  UNIQUE KEY `tmd` (`theme`,`module`,`delta`),
  KEY `list` (`theme`,`status`,`region`,`weight`,`module`)
) ENGINE=InnoDB AUTO_INCREMENT=409 DEFAULT CHARSET=utf8 COMMENT='Stores block settings, such as region and visibility...';
/*!40101 SET character_set_client = @saved_cs_client */;

LOCK TABLES `block` WRITE;
/*!40000 ALTER TABLE `block` DISABLE KEYS */;
INSERT INTO `block` VALUES (1,'system','main','bartik',1,0,'content',0,0,'','',-1);
INSERT INTO `block` VALUES (2,'search','form','bartik',1,-11,'sidebar_first',0,0,'','',-1);
INSERT INTO `block` VALUES (3,'node','recent','seven',1,10,'dashboard_main',0,0,'','',-1);
INSERT INTO `block` VALUES (4,'user','login','bartik',1,-10,'sidebar_first',0,0,'','',-1);
INSERT INTO `block` VALUES (5,'system','navigation','bartik',0,-7,'-1',0,0,'','',-1);
INSERT INTO `block` VALUES (6,'system','powered-by','bartik',1,-8,'footer',0,0,'','',-1);
INSERT INTO `block` VALUES (7,'system','help','bartik',1,-8,'help',0,0,'','',-1);
INSERT INTO `block` VALUES (8,'system','main','seven',1,0,'content',0,0,'','',-1);
INSERT INTO `block` VALUES (9,'system','help','seven',1,0,'help',0,0,'','',-1);
INSERT INTO `block` VALUES (10,'user','login','seven',1,10,'content',0,0,'','',-1);
INSERT INTO `block` VALUES (11,'user','new','seven',1,0,'dashboard_sidebar',0,0,'','',-1);
INSERT INTO `block` VALUES (12,'search','form','seven',1,-10,'dashboard_sidebar',0,0,'','',-1);
INSERT INTO `block` VALUES (13,'comment','recent','bartik',0,-5,'-1',0,0,'','',1);
INSERT INTO `block` VALUES (14,'node','syndicate','bartik',0,-3,'-1',0,0,'','',-1);
INSERT INTO `block` VALUES (15,'node','recent','bartik',0,-4,'-1',0,0,'','',1);
INSERT INTO `block` VALUES (16,'shortcut','shortcuts','bartik',0,0,'-1',0,0,'','',-1);
INSERT INTO `block` VALUES (17,'system','management','bartik',0,-7,'-1',0,0,'','',-1);
INSERT INTO `block` VALUES (18,'system','user-menu','bartik',0,-2,'-1',0,0,'','',-1);
INSERT INTO `block` VALUES (19,'system','main-menu','bartik',0,-8,'-1',0,0,'','',-1);
INSERT INTO `block` VALUES (20,'user','new','bartik',0,0,'-1',0,0,'','',1);
INSERT INTO `block` VALUES (21,'user','online','bartik',0,1,'-1',0,0,'','',-1);
INSERT INTO `block` VALUES (22,'comment','recent','seven',1,0,'dashboard_inactive',0,0,'','',1);
INSERT INTO `block` VALUES (23,'node','syndicate','seven',0,0,'-1',0,0,'','',-1);
INSERT INTO `block` VALUES (24,'shortcut','shortcuts','seven',0,0,'-1',0,0,'','',-1);
INSERT INTO `block` VALUES (25,'system','powered-by','seven',0,10,'-1',0,0,'','',-1);
INSERT INTO `block` VALUES (26,'system','navigation','seven',0,0,'-1',0,0,'','',-1);
INSERT INTO `block` VALUES (27,'system','management','seven',0,0,'-1',0,0,'','',-1);
INSERT INTO `block` VALUES (28,'system','user-menu','seven',0,0,'-1',0,0,'','',-1);
INSERT INTO `block` VALUES (29,'system','main-menu','seven',0,0,'-1',0,0,'','',-1);
INSERT INTO `block` VALUES (30,'user','online','seven',1,0,'dashboard_inactive',0,0,'','',-1);
INSERT INTO `block` VALUES (31,'views','nodequeue_1-block','bartik',0,-6,'-1',0,0,'','',-1);
INSERT INTO `block` VALUES (32,'views','nodequeue_1-block','seven',0,0,'-1',0,0,'','',-1);
INSERT INTO `block` VALUES (33,'menu','menu-webmaster-menu','bartik',1,-9,'sidebar_first',0,0,'<front>','',-1);
INSERT INTO `block` VALUES (34,'menu','menu-webmaster-menu','seven',0,0,'-1',0,0,'<front>','',-1);
INSERT INTO `block` VALUES (35,'views','brag_bar-block','bartik',1,-12,'sidebar_first',0,0,'','',-1);
INSERT INTO `block` VALUES (36,'views','brag_bar-block','seven',0,0,'-1',0,0,'','',-1);
INSERT INTO `block` VALUES (37,'comment','recent','zen',0,-5,'-1',0,0,'','',1);
INSERT INTO `block` VALUES (38,'menu','menu-webmaster-menu','zen',0,-6,'-1',0,0,'<front>','',-1);
INSERT INTO `block` VALUES (39,'node','recent','zen',0,-4,'-1',0,0,'','',1);
INSERT INTO `block` VALUES (40,'node','syndicate','zen',0,-3,'-1',0,0,'','',-1);
INSERT INTO `block` VALUES (41,'search','form','zen',1,-8,'sidebar_first',0,0,'','',-1);
INSERT INTO `block` VALUES (42,'shortcut','shortcuts','zen',0,0,'-1',0,0,'','',-1);
INSERT INTO `block` VALUES (43,'system','help','zen',1,-7,'help',0,0,'','',-1);
INSERT INTO `block` VALUES (44,'system','main','zen',1,0,'content',0,0,'','',-1);
INSERT INTO `block` VALUES (45,'system','main-menu','zen',0,-8,'-1',0,0,'','',-1);
INSERT INTO `block` VALUES (46,'system','management','zen',0,-7,'-1',0,0,'','',-1);
INSERT INTO `block` VALUES (47,'system','navigation','zen',0,-7,'-1',0,0,'','',-1);
INSERT INTO `block` VALUES (48,'system','powered-by','zen',1,-8,'footer',0,0,'','',-1);
INSERT INTO `block` VALUES (49,'system','user-menu','zen',0,-2,'-1',0,0,'','',-1);
INSERT INTO `block` VALUES (50,'user','login','zen',1,-7,'sidebar_first',0,0,'','',-1);
INSERT INTO `block` VALUES (51,'user','new','zen',0,0,'-1',0,0,'','',1);
INSERT INTO `block` VALUES (52,'user','online','zen',0,1,'-1',0,0,'','',-1);
INSERT INTO `block` VALUES (53,'views','brag_bar-block','zen',1,-9,'sidebar_first',0,0,'','',-1);
INSERT INTO `block` VALUES (54,'views','nodequeue_1-block','zen',0,-6,'-1',0,0,'','',-1);
INSERT INTO `block` VALUES (55,'comment','recent','ATD',0,-19,'-1',0,0,'','',1);
INSERT INTO `block` VALUES (56,'menu','menu-webmaster-menu','ATD',1,-25,'sidebar_second',0,0,'<front>','',-1);
INSERT INTO `block` VALUES (57,'node','recent','ATD',0,-18,'-1',0,0,'','',1);
INSERT INTO `block` VALUES (58,'node','syndicate','ATD',0,-17,'-1',0,0,'','',-1);
INSERT INTO `block` VALUES (59,'search','form','ATD',1,-10,'navigation',0,0,'','',-1);
INSERT INTO `block` VALUES (60,'shortcut','shortcuts','ATD',0,0,'-1',0,0,'','',-1);
INSERT INTO `block` VALUES (61,'system','help','ATD',1,-7,'help',0,0,'','',-1);
INSERT INTO `block` VALUES (62,'system','main','ATD',1,-35,'content',0,0,'','',-1);
INSERT INTO `block` VALUES (63,'system','main-menu','ATD',0,-34,'-1',0,0,'','',-1);
INSERT INTO `block` VALUES (64,'system','management','ATD',0,-33,'-1',0,0,'','',-1);
INSERT INTO `block` VALUES (65,'system','navigation','ATD',0,-32,'-1',0,0,'','',-1);
INSERT INTO `block` VALUES (66,'system','powered-by','ATD',0,-31,'-1',0,0,'','',-1);
INSERT INTO `block` VALUES (67,'system','user-menu','ATD',0,-14,'-1',0,0,'','',-1);
INSERT INTO `block` VALUES (68,'user','login','ATD',0,-15,'-1',0,0,'','',-1);
INSERT INTO `block` VALUES (69,'user','new','ATD',0,-11,'-1',0,0,'','',1);
INSERT INTO `block` VALUES (70,'user','online','ATD',0,-10,'-1',0,0,'','',-1);
INSERT INTO `block` VALUES (71,'views','brag_bar-block','ATD',1,-9,'sidebar_first',0,0,'','',-1);
INSERT INTO `block` VALUES (72,'views','nodequeue_1-block','ATD',0,-6,'-1',0,0,'','',-1);
INSERT INTO `block` VALUES (73,'nice_menus','1','ATD',1,-11,'navigation',0,0,'','<none>',-1);
INSERT INTO `block` VALUES (74,'nice_menus','2','ATD',0,0,'-1',0,0,'','',-1);
INSERT INTO `block` VALUES (75,'nice_menus','1','bartik',1,-9,'header',0,0,'','<none>',-1);
INSERT INTO `block` VALUES (76,'nice_menus','2','bartik',0,0,'-1',0,0,'','',-1);
INSERT INTO `block` VALUES (77,'nice_menus','1','seven',0,0,'-1',0,0,'','<none>',-1);
INSERT INTO `block` VALUES (78,'nice_menus','2','seven',0,0,'-1',0,0,'','',-1);
INSERT INTO `block` VALUES (79,'nice_menus','1','zen',0,0,'-1',0,0,'','<none>',-1);
INSERT INTO `block` VALUES (80,'nice_menus','2','zen',0,0,'-1',0,0,'','',-1);
INSERT INTO `block` VALUES (81,'masquerade','masquerade','bartik',1,-8,'sidebar_first',0,0,'<front>','',-1);
INSERT INTO `block` VALUES (82,'masquerade','masquerade','ATD',1,-24,'sidebar_second',0,0,'<front>','',-1);
INSERT INTO `block` VALUES (83,'masquerade','masquerade','seven',0,0,'-1',0,0,'<front>','',-1);
INSERT INTO `block` VALUES (84,'masquerade','masquerade','zen',0,0,'-1',0,0,'<front>','',-1);
INSERT INTO `block` VALUES (85,'views','all_news_feeds-block_1','bartik',0,0,'-1',0,1,'<front>','',-1);
INSERT INTO `block` VALUES (86,'views','all_news_feeds-block_1','ATD',1,-32,'content',0,1,'<front>','',-1);
INSERT INTO `block` VALUES (87,'views','all_news_feeds-block_1','seven',0,0,'-1',0,1,'<front>','',-1);
INSERT INTO `block` VALUES (88,'views','all_news_feeds-block_1','zen',0,0,'-1',0,1,'<front>','',-1);
INSERT INTO `block` VALUES (89,'views','nodequeue_2-block','bartik',0,0,'-1',0,1,'<front>','',-1);
INSERT INTO `block` VALUES (90,'block','1','ATD',1,-34,'content',0,1,'home','Spotlight',-1);
INSERT INTO `block` VALUES (91,'block','1','bartik',0,0,'-1',0,1,'home','Spotlight',-1);
INSERT INTO `block` VALUES (92,'block','1','seven',0,0,'-1',0,1,'home','Spotlight',-1);
INSERT INTO `block` VALUES (93,'block','1','zen',0,0,'-1',0,1,'home','Spotlight',-1);
INSERT INTO `block` VALUES (94,'views','nodequeue_2-block','ATD',1,-33,'content',0,1,'<front>','',-1);
INSERT INTO `block` VALUES (95,'views','nodequeue_2-block','seven',0,0,'-1',0,1,'<front>','',-1);
INSERT INTO `block` VALUES (96,'views','nodequeue_2-block','zen',0,0,'-1',0,1,'<front>','',-1);
INSERT INTO `block` VALUES (97,'views','slideshow-block','ATD',1,-41,'highlighted',0,1,'<front>','<none>',-1);
INSERT INTO `block` VALUES (98,'views','slideshow-block','bartik',0,0,'-1',0,1,'<front>','<none>',-1);
INSERT INTO `block` VALUES (99,'views','slideshow-block','seven',0,0,'-1',0,1,'<front>','<none>',-1);
INSERT INTO `block` VALUES (100,'views','slideshow-block','zen',0,0,'-1',0,1,'<front>','<none>',-1);
INSERT INTO `block` VALUES (101,'views','nodequeue_3-block','bartik',0,0,'-1',0,1,'','Cutting Edge Series',-1);
INSERT INTO `block` VALUES (102,'views','nodequeue_3-block','ATD',0,-27,'-1',0,1,'','Cutting Edge Series',-1);
INSERT INTO `block` VALUES (103,'views','nodequeue_3-block','seven',0,0,'-1',0,1,'','Cutting Edge Series',-1);
INSERT INTO `block` VALUES (104,'views','nodequeue_3-block','zen',0,0,'-1',0,1,'','Cutting Edge Series',-1);
INSERT INTO `block` VALUES (105,'views','nodequeue_4-block','ATD',1,-31,'content',0,1,'resource/2011_promising_practices','<none>',-1);
INSERT INTO `block` VALUES (106,'views','nodequeue_4-block','bartik',1,0,'content',0,1,'resource/2011_promising_practices','<none>',-1);
INSERT INTO `block` VALUES (107,'views','nodequeue_4-block','seven',0,0,'-1',0,1,'resource/2011_promising_practices','<none>',-1);
INSERT INTO `block` VALUES (108,'views','nodequeue_4-block','zen',0,0,'-1',0,1,'resource/2011_promising_practices','<none>',-1);
INSERT INTO `block` VALUES (109,'views','nodequeue_4-block_1','bartik',1,0,'content',0,1,'resource/2010_promising_practices','<none>',-1);
INSERT INTO `block` VALUES (110,'views','nodequeue_4-block_1','ATD',1,-30,'content',0,1,'resource/2010_promising_practices','<none>',-1);
INSERT INTO `block` VALUES (111,'views','nodequeue_4-block_1','seven',0,0,'-1',0,1,'resource/2010_promising_practices','<none>',-1);
INSERT INTO `block` VALUES (112,'views','nodequeue_4-block_1','zen',0,0,'-1',0,1,'resource/2010_promising_practices','<none>',-1);
INSERT INTO `block` VALUES (113,'block','2','ATD',1,-16,'header',0,0,'','',-1);
INSERT INTO `block` VALUES (114,'block','2','bartik',0,0,'-1',0,0,'','',-1);
INSERT INTO `block` VALUES (115,'block','2','seven',0,0,'-1',0,0,'','',-1);
INSERT INTO `block` VALUES (116,'block','2','zen',0,0,'-1',0,0,'','',-1);
INSERT INTO `block` VALUES (117,'block','3','ATD',1,-14,'footer',0,0,'','',-1);
INSERT INTO `block` VALUES (118,'block','3','bartik',0,0,'-1',0,0,'','',-1);
INSERT INTO `block` VALUES (119,'block','3','seven',0,0,'-1',0,0,'','',-1);
INSERT INTO `block` VALUES (120,'block','3','zen',0,0,'-1',0,0,'','',-1);
INSERT INTO `block` VALUES (121,'block','4','ATD',1,-17,'footer',0,0,'','',-1);
INSERT INTO `block` VALUES (122,'block','4','bartik',0,0,'-1',0,0,'','',-1);
INSERT INTO `block` VALUES (123,'block','4','seven',0,0,'-1',0,0,'','',-1);
INSERT INTO `block` VALUES (124,'block','4','zen',0,0,'-1',0,0,'','',-1);
INSERT INTO `block` VALUES (125,'gmap_location','0','ATD',0,-36,'-1',0,0,'','',-1);
INSERT INTO `block` VALUES (126,'gmap_location','1','ATD',0,-39,'-1',0,0,'','',-1);
INSERT INTO `block` VALUES (127,'gmap_location','0','bartik',0,0,'-1',0,0,'','',-1);
INSERT INTO `block` VALUES (128,'gmap_location','1','bartik',0,0,'-1',0,0,'','',-1);
INSERT INTO `block` VALUES (129,'gmap_location','0','seven',0,0,'-1',0,0,'','',-1);
INSERT INTO `block` VALUES (130,'gmap_location','1','seven',0,0,'-1',0,0,'','',-1);
INSERT INTO `block` VALUES (131,'gmap_location','0','zen',0,0,'-1',0,0,'','',-1);
INSERT INTO `block` VALUES (132,'gmap_location','1','zen',0,0,'-1',0,0,'','',-1);
INSERT INTO `block` VALUES (133,'views','map_colleges-block_1','ATD',1,-39,'content',0,1,'network/state_policy_teams','',-1);
INSERT INTO `block` VALUES (134,'views','map_colleges-block_1','bartik',0,0,'-1',0,1,'network/state_policy_teams','',-1);
INSERT INTO `block` VALUES (135,'views','map_colleges-block_1','seven',0,0,'-1',0,1,'network/state_policy_teams','',-1);
INSERT INTO `block` VALUES (136,'views','map_colleges-block_1','zen',0,0,'-1',0,1,'network/state_policy_teams','',-1);
INSERT INTO `block` VALUES (137,'views','nodequeue_6-block','ATD',0,-26,'-1',0,0,'','',-1);
INSERT INTO `block` VALUES (138,'views','nodequeue_6-block','bartik',0,0,'-1',0,0,'','',-1);
INSERT INTO `block` VALUES (139,'views','nodequeue_6-block','seven',0,0,'-1',0,0,'','',-1);
INSERT INTO `block` VALUES (140,'views','nodequeue_6-block','zen',0,0,'-1',0,0,'','',-1);
INSERT INTO `block` VALUES (141,'block','5','ATD',1,-16,'footer',0,0,'','',-1);
INSERT INTO `block` VALUES (142,'block','5','bartik',0,0,'-1',0,0,'','',-1);
INSERT INTO `block` VALUES (143,'block','5','seven',0,0,'-1',0,0,'','',-1);
INSERT INTO `block` VALUES (144,'block','5','zen',0,0,'-1',0,0,'','',-1);
INSERT INTO `block` VALUES (145,'block','6','ATD',1,-15,'footer',0,0,'','',-1);
INSERT INTO `block` VALUES (146,'block','6','bartik',0,0,'-1',0,0,'','',-1);
INSERT INTO `block` VALUES (147,'block','6','seven',0,0,'-1',0,0,'','',-1);
INSERT INTO `block` VALUES (148,'block','6','zen',0,0,'-1',0,0,'','',-1);
INSERT INTO `block` VALUES (149,'views','resources-block_1','ATD',0,0,'-1',0,1,'results/knowledge_center','<none>',-1);
INSERT INTO `block` VALUES (154,'views','resources-block_2','ATD',0,0,'-1',0,0,'','',-1);
INSERT INTO `block` VALUES (155,'views','resources-block_1','bartik',0,0,'-1',0,1,'results/knowledge_center','<none>',-1);
INSERT INTO `block` VALUES (156,'views','resources-block_2','bartik',0,0,'-1',0,0,'','',-1);
INSERT INTO `block` VALUES (157,'views','resources-block_1','seven',0,0,'-1',0,1,'results/knowledge_center','<none>',-1);
INSERT INTO `block` VALUES (158,'views','resources-block_2','seven',0,0,'-1',0,0,'','',-1);
INSERT INTO `block` VALUES (159,'views','resources-block_1','zen',0,0,'-1',0,1,'results/knowledge_center','<none>',-1);
INSERT INTO `block` VALUES (160,'views','resources-block_2','zen',0,0,'-1',0,0,'','',-1);
INSERT INTO `block` VALUES (161,'views','nodequeue_7-block','ATD',0,-24,'-1',0,0,'','',-1);
INSERT INTO `block` VALUES (162,'views','nodequeue_7-block','bartik',0,0,'-1',0,0,'','',-1);
INSERT INTO `block` VALUES (163,'views','nodequeue_7-block','seven',0,0,'-1',0,0,'','',-1);
INSERT INTO `block` VALUES (164,'views','nodequeue_7-block','zen',0,0,'-1',0,0,'','',-1);
INSERT INTO `block` VALUES (165,'block','8','ATD',1,-40,'sidebar_second',0,0,'<front>','',-1);
INSERT INTO `block` VALUES (166,'block','8','bartik',0,0,'-1',0,0,'<front>','',-1);
INSERT INTO `block` VALUES (167,'block','8','seven',0,0,'-1',0,0,'<front>','',-1);
INSERT INTO `block` VALUES (168,'block','8','zen',0,0,'-1',0,0,'<front>','',-1);
INSERT INTO `block` VALUES (169,'views','nodequeue_8-block','ATD',0,-25,'-1',0,0,'','',-1);
INSERT INTO `block` VALUES (170,'views','nodequeue_8-block','bartik',0,0,'-1',0,0,'','',-1);
INSERT INTO `block` VALUES (171,'views','nodequeue_8-block','seven',0,0,'-1',0,0,'','',-1);
INSERT INTO `block` VALUES (172,'views','nodequeue_8-block','zen',0,0,'-1',0,0,'','',-1);
INSERT INTO `block` VALUES (173,'block','9','ATD',1,-29,'content',0,1,'college_profile/*','The Achieving the Dream Model',-1);
INSERT INTO `block` VALUES (174,'block','9','bartik',0,0,'-1',0,1,'college_profile/*','The Achieving the Dream Model',-1);
INSERT INTO `block` VALUES (175,'block','9','seven',0,0,'-1',0,1,'college_profile/*','The Achieving the Dream Model',-1);
INSERT INTO `block` VALUES (176,'block','9','zen',0,0,'-1',0,1,'college_profile/*','The Achieving the Dream Model',-1);
INSERT INTO `block` VALUES (177,'block','10','ATD',1,-28,'content',0,1,'college_profile/*','Achieving the Dream Leader Colleges',-1);
INSERT INTO `block` VALUES (178,'block','10','bartik',0,0,'-1',0,1,'college_profile/*','Achieving the Dream Leader Colleges',-1);
INSERT INTO `block` VALUES (179,'block','10','seven',0,0,'-1',0,1,'college_profile/*','Achieving the Dream Leader Colleges',-1);
INSERT INTO `block` VALUES (180,'block','10','zen',0,0,'-1',0,1,'college_profile/*','Achieving the Dream Leader Colleges',-1);
INSERT INTO `block` VALUES (181,'views','-exp-resources-page_7','ATD',0,-37,'-1',0,0,'','Search the Knowledge Center',-1);
INSERT INTO `block` VALUES (182,'views','-exp-resources-page_7','bartik',0,0,'-1',0,0,'','',-1);
INSERT INTO `block` VALUES (183,'views','-exp-resources-page_7','seven',0,0,'-1',0,0,'','',-1);
INSERT INTO `block` VALUES (184,'views','-exp-resources-page_7','zen',0,0,'-1',0,0,'','',-1);
INSERT INTO `block` VALUES (185,'views','map_colleges-block_2','ATD',1,-27,'content',0,1,'map/colleges\r\napproach/institutional_change/participating_institutions\r\nnetwork/institutions','Participating Institutions',-1);
INSERT INTO `block` VALUES (186,'views','map_colleges-block_2','bartik',0,0,'-1',0,1,'map/colleges\r\napproach/institutional_change/participating_institutions\r\nnetwork/institutions','Participating Institutions',-1);
INSERT INTO `block` VALUES (187,'views','map_colleges-block_2','seven',0,0,'-1',0,1,'map/colleges\r\napproach/institutional_change/participating_institutions\r\nnetwork/institutions','Participating Institutions',-1);
INSERT INTO `block` VALUES (188,'views','map_colleges-block_2','zen',0,0,'-1',0,1,'map/colleges\r\napproach/institutional_change/participating_institutions\r\nnetwork/institutions','Participating Institutions',-1);
INSERT INTO `block` VALUES (189,'views','map_colleges-block_3','ATD',0,-13,'-1',0,1,'map/colleges','',-1);
INSERT INTO `block` VALUES (190,'views','map_colleges-block_3','bartik',0,0,'-1',0,1,'map/colleges','',-1);
INSERT INTO `block` VALUES (191,'views','map_colleges-block_3','seven',0,0,'-1',0,1,'map/colleges','',-1);
INSERT INTO `block` VALUES (192,'views','map_colleges-block_3','zen',0,0,'-1',0,1,'map/colleges','',-1);
INSERT INTO `block` VALUES (193,'block','11','ATD',1,-38,'content',0,1,'contact','',-1);
INSERT INTO `block` VALUES (194,'block','11','bartik',0,0,'-1',0,1,'contact','',-1);
INSERT INTO `block` VALUES (195,'block','11','seven',0,0,'-1',0,1,'contact','',-1);
INSERT INTO `block` VALUES (196,'block','11','zen',0,0,'-1',0,1,'contact','',-1);
INSERT INTO `block` VALUES (197,'views','nodequeue_9-block','ATD',0,-29,'-1',0,0,'','',-1);
INSERT INTO `block` VALUES (198,'views','nodequeue_9-block','bartik',0,0,'-1',0,0,'','',-1);
INSERT INTO `block` VALUES (199,'views','nodequeue_9-block','seven',0,0,'-1',0,0,'','',-1);
INSERT INTO `block` VALUES (200,'views','nodequeue_9-block','zen',0,0,'-1',0,0,'','',-1);
INSERT INTO `block` VALUES (201,'block','12','ATD',1,-37,'content',0,1,'map/colleges\r\nmap/colleges/*\r\napproach/institutional_change/participating_institutions\r\nnetwork/institutions','',-1);
INSERT INTO `block` VALUES (202,'block','12','bartik',0,0,'-1',0,1,'map/colleges\r\nmap/colleges/*\r\napproach/institutional_change/participating_institutions\r\nnetwork/institutions','',-1);
INSERT INTO `block` VALUES (203,'block','12','seven',0,0,'-1',0,1,'map/colleges\r\nmap/colleges/*\r\napproach/institutional_change/participating_institutions\r\nnetwork/institutions','',-1);
INSERT INTO `block` VALUES (204,'block','12','zen',0,0,'-1',0,1,'map/colleges\r\nmap/colleges/*\r\napproach/institutional_change/participating_institutions\r\nnetwork/institutions','',-1);
INSERT INTO `block` VALUES (205,'views','map_colleges-block_4','ATD',1,-23,'content',0,1,'map/colleges/leader_colleges','',-1);
INSERT INTO `block` VALUES (206,'views','map_colleges-block_4','bartik',0,0,'-1',0,0,'map/colleges/leader_colleges','',-1);
INSERT INTO `block` VALUES (207,'views','map_colleges-block_4','seven',0,0,'-1',0,0,'map/colleges/leader_colleges','',-1);
INSERT INTO `block` VALUES (208,'views','map_colleges-block_4','zen',0,0,'-1',0,0,'map/colleges/leader_colleges','',-1);
INSERT INTO `block` VALUES (209,'views','map_colleges-block_5','ATD',1,-24,'content',0,1,'map/colleges/former_leader_colleges','',-1);
INSERT INTO `block` VALUES (210,'views','map_colleges-block_5','bartik',0,0,'-1',0,1,'map/colleges/former_leader_colleges','',-1);
INSERT INTO `block` VALUES (211,'views','map_colleges-block_5','seven',0,0,'-1',0,1,'map/colleges/former_leader_colleges','',-1);
INSERT INTO `block` VALUES (212,'views','map_colleges-block_5','zen',0,0,'-1',0,1,'map/colleges/former_leader_colleges','',-1);
INSERT INTO `block` VALUES (213,'views','map_colleges-block_6','ATD',1,-25,'content',0,1,'map/colleges/former_institutions','',-1);
INSERT INTO `block` VALUES (214,'views','map_colleges-block_6','bartik',0,0,'-1',0,0,'map/colleges/former_institutions','',-1);
INSERT INTO `block` VALUES (215,'views','map_colleges-block_6','seven',0,0,'-1',0,0,'map/colleges/former_institutions','',-1);
INSERT INTO `block` VALUES (216,'views','map_colleges-block_6','zen',0,0,'-1',0,0,'map/colleges/former_institutions','',-1);
INSERT INTO `block` VALUES (217,'block','13','ATD',0,-9,'-1',0,0,'','or Search by Keyword',-1);
INSERT INTO `block` VALUES (218,'block','13','bartik',0,0,'-1',0,0,'','or Search by Keyword',-1);
INSERT INTO `block` VALUES (219,'block','13','seven',0,0,'-1',0,0,'','or Search by Keyword',-1);
INSERT INTO `block` VALUES (220,'block','13','zen',0,0,'-1',0,0,'','or Search by Keyword',-1);
INSERT INTO `block` VALUES (221,'block','14','ATD',1,-26,'sidebar_second',0,1,'about','',-1);
INSERT INTO `block` VALUES (222,'block','14','bartik',0,0,'-1',0,1,'about','',-1);
INSERT INTO `block` VALUES (223,'block','14','seven',0,0,'-1',0,1,'about','',-1);
INSERT INTO `block` VALUES (224,'block','14','zen',0,0,'-1',0,1,'about','',-1);
INSERT INTO `block` VALUES (225,'block','15','ATD',1,-35,'sidebar_second',0,1,'map/colleges/leader_colleges','Requirements',-1);
INSERT INTO `block` VALUES (226,'block','15','bartik',0,0,'-1',0,1,'map/colleges/leader_colleges','Requirements',-1);
INSERT INTO `block` VALUES (227,'block','15','seven',0,0,'-1',0,1,'map/colleges/leader_colleges','Requirements',-1);
INSERT INTO `block` VALUES (228,'block','15','zen',0,0,'-1',0,1,'map/colleges/leader_colleges','Requirements',-1);
INSERT INTO `block` VALUES (229,'views','map_colleges-block_7','ATD',1,-26,'content',0,1,'map/colleges/all\r\napproach/institutional_change/participating_institutions\r\nnetwork/institutions','',-1);
INSERT INTO `block` VALUES (230,'views','map_colleges-block_7','bartik',0,0,'-1',0,1,'map/colleges/all\r\napproach/institutional_change/participating_institutions\r\nnetwork/institutions','',-1);
INSERT INTO `block` VALUES (231,'views','map_colleges-block_7','seven',0,0,'-1',0,1,'map/colleges/all\r\napproach/institutional_change/participating_institutions\r\nnetwork/institutions','',-1);
INSERT INTO `block` VALUES (232,'views','map_colleges-block_7','zen',0,0,'-1',0,1,'map/colleges/all\r\napproach/institutional_change/participating_institutions\r\nnetwork/institutions','',-1);
INSERT INTO `block` VALUES (233,'block','16','ATD',1,-41,'sidebar_second',0,0,'<front>','',-1);
INSERT INTO `block` VALUES (234,'block','16','bartik',0,0,'-1',0,0,'<front>','',-1);
INSERT INTO `block` VALUES (235,'block','16','seven',0,0,'-1',0,0,'<front>','',-1);
INSERT INTO `block` VALUES (236,'block','16','zen',0,0,'-1',0,0,'<front>','',-1);
INSERT INTO `block` VALUES (237,'views','archive-block','ATD',1,-27,'sidebar_second',0,1,'blog/*\r\nblog\r\ntopics/*','',-1);
INSERT INTO `block` VALUES (238,'views','archive-block','bartik',0,0,'-1',0,1,'blog/*\r\nblog\r\ntopics/*','',-1);
INSERT INTO `block` VALUES (239,'views','archive-block','seven',0,0,'-1',0,1,'blog/*\r\nblog\r\ntopics/*','',-1);
INSERT INTO `block` VALUES (240,'views','archive-block','zen',0,0,'-1',0,1,'blog/*\r\nblog\r\ntopics/*','',-1);
INSERT INTO `block` VALUES (241,'block','17','ATD',0,-38,'-1',0,1,'blog\r\nblog/*','Blogroll',-1);
INSERT INTO `block` VALUES (242,'block','17','bartik',0,0,'-1',0,1,'blog\r\nblog/*','Blogroll',-1);
INSERT INTO `block` VALUES (243,'block','17','seven',0,0,'-1',0,1,'blog\r\nblog/*','Blogroll',-1);
INSERT INTO `block` VALUES (244,'block','17','zen',0,0,'-1',0,1,'blog\r\nblog/*','Blogroll',-1);
INSERT INTO `block` VALUES (245,'block','18','ATD',1,-32,'sidebar_second',0,1,'dream2013*\r\ntest-panel/DREAM2013*','',-1);
INSERT INTO `block` VALUES (246,'block','18','bartik',0,0,'-1',0,1,'dream2013*\r\ntest-panel/DREAM2013*','',-1);
INSERT INTO `block` VALUES (247,'block','18','seven',0,0,'-1',0,1,'dream2013*\r\ntest-panel/DREAM2013*','',-1);
INSERT INTO `block` VALUES (248,'block','18','zen',0,0,'-1',0,1,'dream2013*\r\ntest-panel/DREAM2013*','',-1);
INSERT INTO `block` VALUES (249,'views','nodequeue_10-block','ATD',0,-23,'-1',0,0,'','',-1);
INSERT INTO `block` VALUES (250,'views','nodequeue_10-block','bartik',0,0,'-1',0,0,'','',-1);
INSERT INTO `block` VALUES (251,'views','nodequeue_10-block','seven',0,0,'-1',0,0,'','',-1);
INSERT INTO `block` VALUES (252,'views','nodequeue_10-block','zen',0,0,'-1',0,0,'','',-1);
INSERT INTO `block` VALUES (253,'menu','menu-dream-2012','ATD',1,-37,'sidebar_second',0,1,'dream2012\r\ndream2012*\r\nresources/recommended\r\nresources/must-read\r\nresources/must_read','',-1);
INSERT INTO `block` VALUES (254,'menu','menu-dream-2012','bartik',0,0,'-1',0,1,'dream2012\r\ndream2012*\r\nresources/recommended\r\nresources/must-read\r\nresources/must_read','',-1);
INSERT INTO `block` VALUES (255,'menu','menu-dream-2012','seven',0,0,'-1',0,1,'dream2012\r\ndream2012*\r\nresources/recommended\r\nresources/must-read\r\nresources/must_read','',-1);
INSERT INTO `block` VALUES (256,'menu','menu-dream-2012','zen',0,0,'-1',0,1,'dream2012\r\ndream2012*\r\nresources/recommended\r\nresources/must-read\r\nresources/must_read','',-1);
INSERT INTO `block` VALUES (257,'views','nodequeue_11-block','ATD',0,-28,'-1',0,0,'','',-1);
INSERT INTO `block` VALUES (258,'views','nodequeue_11-block','bartik',0,0,'-1',0,0,'','',-1);
INSERT INTO `block` VALUES (259,'views','nodequeue_11-block','seven',0,0,'-1',0,0,'','',-1);
INSERT INTO `block` VALUES (260,'views','nodequeue_11-block','zen',0,0,'-1',0,0,'','',-1);
INSERT INTO `block` VALUES (261,'aggregator','feed-1','ATD',0,-15,'-1',0,1,'test_flickr_slideshow','Photos from Wednesday',1);
INSERT INTO `block` VALUES (262,'views','f7b820b031c497e6ab80ca074c4b184c','ATD',1,-40,'content',0,1,'test_flickr_slideshow','',-1);
INSERT INTO `block` VALUES (263,'aggregator','feed-1','bartik',0,0,'-1',0,1,'test_flickr_slideshow','Photos from Wednesday',1);
INSERT INTO `block` VALUES (264,'views','f7b820b031c497e6ab80ca074c4b184c','bartik',0,0,'-1',0,1,'test_flickr_slideshow','',-1);
INSERT INTO `block` VALUES (265,'aggregator','feed-1','seven',0,0,'-1',0,1,'test_flickr_slideshow','Photos from Wednesday',1);
INSERT INTO `block` VALUES (266,'views','f7b820b031c497e6ab80ca074c4b184c','seven',0,0,'-1',0,1,'test_flickr_slideshow','',-1);
INSERT INTO `block` VALUES (267,'aggregator','feed-1','zen',0,0,'-1',0,1,'test_flickr_slideshow','Photos from Wednesday',1);
INSERT INTO `block` VALUES (268,'views','f7b820b031c497e6ab80ca074c4b184c','zen',0,0,'-1',0,1,'test_flickr_slideshow','',-1);
INSERT INTO `block` VALUES (269,'views','popular-block','ATD',1,-28,'sidebar_second',0,1,'blog\r\nblog*\r\ntopics/*','',-1);
INSERT INTO `block` VALUES (270,'views','popular-block_1','ATD',0,-12,'-1',0,0,'','',-1);
INSERT INTO `block` VALUES (271,'views','popular-block','bartik',0,0,'-1',0,1,'blog\r\nblog*\r\ntopics/*','',-1);
INSERT INTO `block` VALUES (272,'views','popular-block_1','bartik',0,0,'-1',0,0,'','',-1);
INSERT INTO `block` VALUES (273,'views','popular-block','seven',0,0,'-1',0,1,'blog\r\nblog*\r\ntopics/*','',-1);
INSERT INTO `block` VALUES (274,'views','popular-block_1','seven',0,0,'-1',0,0,'','',-1);
INSERT INTO `block` VALUES (275,'views','popular-block','zen',0,0,'-1',0,1,'blog\r\nblog*\r\ntopics/*','',-1);
INSERT INTO `block` VALUES (276,'views','popular-block_1','zen',0,0,'-1',0,0,'','',-1);
INSERT INTO `block` VALUES (277,'statistics','popular','ATD',0,-28,'-1',0,0,'','',-1);
INSERT INTO `block` VALUES (278,'statistics','popular','bartik',0,0,'-1',0,0,'','',-1);
INSERT INTO `block` VALUES (279,'statistics','popular','seven',0,0,'-1',0,0,'','',-1);
INSERT INTO `block` VALUES (280,'statistics','popular','zen',0,0,'-1',0,0,'','',-1);
INSERT INTO `block` VALUES (281,'tagadelic','5','ATD',0,-16,'-1',0,0,'','',8);
INSERT INTO `block` VALUES (282,'tagadelic','2','ATD',0,-15,'-1',0,0,'','',8);
INSERT INTO `block` VALUES (283,'tagadelic','8','ATD',0,-14,'-1',0,0,'','',8);
INSERT INTO `block` VALUES (284,'tagadelic','7','ATD',0,-13,'-1',0,0,'','',8);
INSERT INTO `block` VALUES (285,'tagadelic','6','ATD',0,-12,'-1',0,0,'','',8);
INSERT INTO `block` VALUES (286,'tagadelic','3','ATD',0,-11,'-1',0,0,'','',8);
INSERT INTO `block` VALUES (287,'tagadelic','4','ATD',0,-31,'-1',0,1,'blog\r\nblog*','Topics',8);
INSERT INTO `block` VALUES (288,'tagadelic','5','bartik',0,0,'-1',0,0,'','',8);
INSERT INTO `block` VALUES (289,'tagadelic','2','bartik',0,0,'-1',0,0,'','',8);
INSERT INTO `block` VALUES (290,'tagadelic','8','bartik',0,0,'-1',0,0,'','',8);
INSERT INTO `block` VALUES (291,'tagadelic','7','bartik',0,0,'-1',0,0,'','',8);
INSERT INTO `block` VALUES (292,'tagadelic','6','bartik',0,0,'-1',0,0,'','',8);
INSERT INTO `block` VALUES (293,'tagadelic','3','bartik',0,0,'-1',0,0,'','',8);
INSERT INTO `block` VALUES (294,'tagadelic','4','bartik',0,0,'-1',0,1,'blog\r\nblog*','Topics',8);
INSERT INTO `block` VALUES (295,'tagadelic','5','seven',0,0,'-1',0,0,'','',8);
INSERT INTO `block` VALUES (296,'tagadelic','2','seven',0,0,'-1',0,0,'','',8);
INSERT INTO `block` VALUES (297,'tagadelic','8','seven',0,0,'-1',0,0,'','',8);
INSERT INTO `block` VALUES (298,'tagadelic','7','seven',0,0,'-1',0,0,'','',8);
INSERT INTO `block` VALUES (299,'tagadelic','6','seven',0,0,'-1',0,0,'','',8);
INSERT INTO `block` VALUES (300,'tagadelic','3','seven',0,0,'-1',0,0,'','',8);
INSERT INTO `block` VALUES (301,'tagadelic','4','seven',0,0,'-1',0,1,'blog\r\nblog*','Topics',8);
INSERT INTO `block` VALUES (302,'tagadelic','5','zen',0,0,'-1',0,0,'','',8);
INSERT INTO `block` VALUES (303,'tagadelic','2','zen',0,0,'-1',0,0,'','',8);
INSERT INTO `block` VALUES (304,'tagadelic','8','zen',0,0,'-1',0,0,'','',8);
INSERT INTO `block` VALUES (305,'tagadelic','7','zen',0,0,'-1',0,0,'','',8);
INSERT INTO `block` VALUES (306,'tagadelic','6','zen',0,0,'-1',0,0,'','',8);
INSERT INTO `block` VALUES (307,'tagadelic','3','zen',0,0,'-1',0,0,'','',8);
INSERT INTO `block` VALUES (308,'tagadelic','4','zen',0,0,'-1',0,1,'blog\r\nblog*','Topics',8);
INSERT INTO `block` VALUES (309,'views','blog_topic_list-block','ATD',1,-29,'sidebar_second',0,1,'blog\r\nblog*\r\ntopics/*','',-1);
INSERT INTO `block` VALUES (310,'views','blog_topic_list-block','bartik',0,0,'-1',0,1,'blog\r\nblog*\r\ntopics/*','',-1);
INSERT INTO `block` VALUES (311,'views','blog_topic_list-block','seven',0,0,'-1',0,1,'blog\r\nblog*\r\ntopics/*','',-1);
INSERT INTO `block` VALUES (312,'views','blog_topic_list-block','zen',0,0,'-1',0,1,'blog\r\nblog*\r\ntopics/*','',-1);
INSERT INTO `block` VALUES (313,'views','blog_posts_by_person-block','ATD',1,-22,'content',0,1,'people*','',-1);
INSERT INTO `block` VALUES (314,'views','blog_posts_by_person-block','bartik',0,0,'-1',0,0,'people*','',-1);
INSERT INTO `block` VALUES (315,'views','blog_posts_by_person-block','seven',0,0,'-1',0,0,'people*','',-1);
INSERT INTO `block` VALUES (316,'views','blog_posts_by_person-block','zen',0,0,'-1',0,0,'people*','',-1);
INSERT INTO `block` VALUES (317,'views','all_news_feeds-block_2','ATD',1,-36,'content',0,1,'taxonomy/term/*\r\ntopic*','',-1);
INSERT INTO `block` VALUES (318,'views','all_news_feeds-block_2','bartik',0,0,'-1',0,1,'taxonomy/term/*\r\ntopic*','',-1);
INSERT INTO `block` VALUES (319,'views','all_news_feeds-block_2','seven',0,0,'-1',0,1,'taxonomy/term/*\r\ntopic*','',-1);
INSERT INTO `block` VALUES (320,'views','all_news_feeds-block_2','zen',0,0,'-1',0,1,'taxonomy/term/*\r\ntopic*','',-1);
INSERT INTO `block` VALUES (321,'block','19','ATD',1,-31,'sidebar_second',0,1,'retreat\r\nretreat/*','2012 Spring Retreat',-1);
INSERT INTO `block` VALUES (322,'block','19','bartik',0,0,'-1',0,1,'retreat\r\nretreat/*','2012 Spring Retreat',-1);
INSERT INTO `block` VALUES (323,'block','19','seven',0,0,'-1',0,1,'retreat\r\nretreat/*','2012 Spring Retreat',-1);
INSERT INTO `block` VALUES (324,'block','19','zen',0,0,'-1',0,1,'retreat\r\nretreat/*','2012 Spring Retreat',-1);
INSERT INTO `block` VALUES (325,'menu_block','1','ATD',1,-36,'sidebar_second',0,1,'logo_identity_standards\r\nlogo_identity_standards*','Logos and Identity Standards Guides',-1);
INSERT INTO `block` VALUES (326,'menu_block','1','bartik',0,0,'-1',0,1,'logo_identity_standards\r\nlogo_identity_standards*','Logos and Identity Standards Guides',-1);
INSERT INTO `block` VALUES (327,'menu_block','1','seven',0,0,'-1',0,1,'logo_identity_standards\r\nlogo_identity_standards*','Logos and Identity Standards Guides',-1);
INSERT INTO `block` VALUES (328,'menu_block','1','zen',0,0,'-1',0,1,'logo_identity_standards\r\nlogo_identity_standards*','Logos and Identity Standards Guides',-1);
INSERT INTO `block` VALUES (329,'menu','menu-logo-and-identity-standards','ATD',0,-35,'-1',0,0,'','',-1);
INSERT INTO `block` VALUES (330,'menu','menu-logo-and-identity-standards','bartik',0,0,'-1',0,0,'','',-1);
INSERT INTO `block` VALUES (331,'menu','menu-logo-and-identity-standards','seven',0,0,'-1',0,0,'','',-1);
INSERT INTO `block` VALUES (332,'menu','menu-logo-and-identity-standards','zen',0,0,'-1',0,0,'','',-1);
INSERT INTO `block` VALUES (333,'menu_block','2','ATD',0,-30,'-1',0,1,'goal\r\napproach\r\nabout/network\r\nnetwork\r\nresults\r\nresources\r\ninitiatives\r\nget_involved\r\nabout','<none>',-1);
INSERT INTO `block` VALUES (334,'menu_block','2','bartik',0,0,'-1',0,1,'goal\r\napproach\r\nabout/network\r\nnetwork\r\nresults\r\nresources\r\ninitiatives\r\nget_involved\r\nabout','<none>',-1);
INSERT INTO `block` VALUES (335,'menu_block','2','seven',0,0,'-1',0,1,'goal\r\napproach\r\nabout/network\r\nnetwork\r\nresults\r\nresources\r\ninitiatives\r\nget_involved\r\nabout','<none>',-1);
INSERT INTO `block` VALUES (336,'menu_block','2','zen',0,0,'-1',0,1,'goal\r\napproach\r\nabout/network\r\nnetwork\r\nresults\r\nresources\r\ninitiatives\r\nget_involved\r\nabout','<none>',-1);
INSERT INTO `block` VALUES (337,'views','nodequeue_12-block','ATD',0,-22,'-1',0,0,'','',-1);
INSERT INTO `block` VALUES (338,'views','nodequeue_12-block','bartik',0,0,'-1',0,0,'','',-1);
INSERT INTO `block` VALUES (339,'views','nodequeue_12-block','seven',0,0,'-1',0,0,'','',-1);
INSERT INTO `block` VALUES (340,'views','nodequeue_12-block','zen',0,0,'-1',0,0,'','',-1);
INSERT INTO `block` VALUES (341,'block','20','ATD',1,-34,'sidebar_second',0,1,'PRESS_grant_resources*','2012 Walmart Kickoff',-1);
INSERT INTO `block` VALUES (342,'block','20','bartik',0,0,'-1',0,1,'PRESS_grant_resources*','2012 Walmart Kickoff',-1);
INSERT INTO `block` VALUES (343,'block','20','seven',0,0,'-1',0,1,'PRESS_grant_resources*','2012 Walmart Kickoff',-1);
INSERT INTO `block` VALUES (344,'block','20','zen',0,0,'-1',0,1,'PRESS_grant_resources*','2012 Walmart Kickoff',-1);
INSERT INTO `block` VALUES (349,'block','22','ATD',1,-33,'sidebar_second',0,1,'kickoff2012_resources*','Additional Kickoff Institute Resources',-1);
INSERT INTO `block` VALUES (350,'block','22','bartik',0,0,'-1',0,1,'kickoff2012_resources*','Additional Kickoff Institute Resources',-1);
INSERT INTO `block` VALUES (351,'block','22','seven',0,0,'-1',0,1,'kickoff2012_resources*','Additional Kickoff Institute Resources',-1);
INSERT INTO `block` VALUES (352,'block','22','zen',0,0,'-1',0,1,'kickoff2012_resources*','Additional Kickoff Institute Resources',-1);
INSERT INTO `block` VALUES (353,'menu','menu-dream-2013','ATD',1,-38,'sidebar_second',0,1,'dream2013\r\ndream2013/*','',-1);
INSERT INTO `block` VALUES (354,'menu','menu-dream-2013','bartik',0,0,'-1',0,1,'dream2013\r\ndream2013/*','',-1);
INSERT INTO `block` VALUES (355,'menu','menu-dream-2013','seven',0,0,'-1',0,1,'dream2013\r\ndream2013/*','',-1);
INSERT INTO `block` VALUES (356,'menu','menu-dream-2013','zen',0,0,'-1',0,1,'dream2013\r\ndream2013/*','',-1);
INSERT INTO `block` VALUES (357,'faq','faq_categories','ATD',0,0,'-1',0,1,'dream2013\r\ndream2013/*','',1);
INSERT INTO `block` VALUES (358,'faq_ask','unanswered','ATD',1,-23,'sidebar_second',0,0,'<front>','Unanswered Questions',1);
INSERT INTO `block` VALUES (359,'faq_ask','ask_a_question','ATD',0,-22,'-1',0,1,'DREAM2013\r\nDREAM2013/*','',8);
INSERT INTO `block` VALUES (360,'views','faq-faq_recent','ATD',0,-20,'-1',0,0,'','',-1);
INSERT INTO `block` VALUES (361,'views','faq-faq_random','ATD',0,-21,'-1',0,0,'','',-1);
INSERT INTO `block` VALUES (362,'faq','faq_categories','bartik',0,0,'-1',0,1,'dream2013\r\ndream2013/*','',1);
INSERT INTO `block` VALUES (363,'faq_ask','unanswered','bartik',0,0,'-1',0,0,'<front>','Unanswered Questions',1);
INSERT INTO `block` VALUES (364,'faq_ask','ask_a_question','bartik',0,-1,'-1',0,1,'DREAM2013\r\nDREAM2013/*','',8);
INSERT INTO `block` VALUES (365,'views','faq-faq_recent','bartik',0,0,'-1',0,0,'','',-1);
INSERT INTO `block` VALUES (366,'views','faq-faq_random','bartik',0,0,'-1',0,0,'','',-1);
INSERT INTO `block` VALUES (367,'faq','faq_categories','seven',0,0,'-1',0,1,'dream2013\r\ndream2013/*','',1);
INSERT INTO `block` VALUES (368,'faq_ask','unanswered','seven',0,0,'-1',0,0,'<front>','Unanswered Questions',1);
INSERT INTO `block` VALUES (369,'faq_ask','ask_a_question','seven',0,-1,'-1',0,1,'DREAM2013\r\nDREAM2013/*','',8);
INSERT INTO `block` VALUES (370,'views','faq-faq_recent','seven',0,0,'-1',0,0,'','',-1);
INSERT INTO `block` VALUES (371,'views','faq-faq_random','seven',0,0,'-1',0,0,'','',-1);
INSERT INTO `block` VALUES (372,'faq','faq_categories','zen',0,0,'-1',0,1,'dream2013\r\ndream2013/*','',1);
INSERT INTO `block` VALUES (373,'faq_ask','unanswered','zen',0,0,'-1',0,0,'<front>','Unanswered Questions',1);
INSERT INTO `block` VALUES (374,'faq_ask','ask_a_question','zen',0,-1,'-1',0,1,'DREAM2013\r\nDREAM2013/*','',8);
INSERT INTO `block` VALUES (375,'views','faq-faq_recent','zen',0,0,'-1',0,0,'','',-1);
INSERT INTO `block` VALUES (376,'views','faq-faq_random','zen',0,0,'-1',0,0,'','',-1);
INSERT INTO `block` VALUES (377,'block','23','ATD',0,0,'-1',0,1,'','',-1);
INSERT INTO `block` VALUES (378,'block','23','bartik',0,0,'-1',0,1,'','',-1);
INSERT INTO `block` VALUES (379,'block','23','seven',0,0,'-1',0,1,'','',-1);
INSERT INTO `block` VALUES (380,'block','23','zen',0,0,'-1',0,1,'','',-1);
INSERT INTO `block` VALUES (381,'views','interventions-block_1','ATD',1,-39,'sidebar_second',0,1,'intervention/intensive_case_management','',-1);
INSERT INTO `block` VALUES (382,'views','interventions-block_1','bartik',0,0,'-1',0,0,'intervention/intensive_case_management','',-1);
INSERT INTO `block` VALUES (383,'views','interventions-block_1','seven',0,0,'-1',0,0,'intervention/intensive_case_management','',-1);
INSERT INTO `block` VALUES (384,'views','interventions-block_1','zen',0,0,'-1',0,0,'intervention/intensive_case_management','',-1);
INSERT INTO `block` VALUES (385,'block','24','ATD',1,-41,'highlighted',0,1,'DREAM2013/*\r\nDREAM2013','',-1);
INSERT INTO `block` VALUES (386,'block','24','bartik',0,0,'-1',0,1,'DREAM2013/*\r\nDREAM2013','',-1);
INSERT INTO `block` VALUES (387,'block','24','seven',0,0,'-1',0,1,'DREAM2013/*\r\nDREAM2013','',-1);
INSERT INTO `block` VALUES (388,'block','24','zen',0,0,'-1',0,1,'DREAM2013/*\r\nDREAM2013','',-1);
INSERT INTO `block` VALUES (389,'views','slideshow-block_best_of_dream','ATD',0,0,'-1',0,0,'','',-1);
INSERT INTO `block` VALUES (390,'views','nodequeue_13-block','ATD',0,0,'-1',0,0,'','',-1);
INSERT INTO `block` VALUES (391,'views','slideshow-block_best_of_dream','bartik',0,0,'-1',0,0,'','',-1);
INSERT INTO `block` VALUES (392,'views','nodequeue_13-block','bartik',0,0,'-1',0,0,'','',-1);
INSERT INTO `block` VALUES (393,'views','slideshow-block_best_of_dream','seven',0,0,'-1',0,0,'','',-1);
INSERT INTO `block` VALUES (394,'views','nodequeue_13-block','seven',0,0,'-1',0,0,'','',-1);
INSERT INTO `block` VALUES (395,'views','slideshow-block_best_of_dream','zen',0,0,'-1',0,0,'','',-1);
INSERT INTO `block` VALUES (396,'views','nodequeue_13-block','zen',0,0,'-1',0,0,'','',-1);
INSERT INTO `block` VALUES (397,'views','slideshow-block_1','ATD',0,0,'-1',0,0,'','',-1);
INSERT INTO `block` VALUES (398,'views','slideshow-block_1','bartik',0,0,'-1',0,0,'','',-1);
INSERT INTO `block` VALUES (399,'views','slideshow-block_1','seven',0,0,'-1',0,0,'','',-1);
INSERT INTO `block` VALUES (400,'views','slideshow-block_1','zen',0,0,'-1',0,0,'','',-1);
INSERT INTO `block` VALUES (401,'block','25','ATD',1,-30,'sidebar_second',0,1,'2012FallCoachRetreat','2012 Fall Retreat',-1);
INSERT INTO `block` VALUES (402,'block','25','bartik',0,0,'-1',0,1,'2012FallCoachRetreat','2012 Fall Retreat',-1);
INSERT INTO `block` VALUES (403,'block','25','seven',0,0,'-1',0,1,'2012FallCoachRetreat','2012 Fall Retreat',-1);
INSERT INTO `block` VALUES (404,'block','25','zen',0,0,'-1',0,1,'2012FallCoachRetreat','2012 Fall Retreat',-1);
INSERT INTO `block` VALUES (405,'menu','features','ATD',0,0,'-1',0,0,'','',-1);
INSERT INTO `block` VALUES (406,'menu','features','bartik',0,0,'-1',0,0,'','',-1);
INSERT INTO `block` VALUES (407,'menu','features','seven',0,0,'-1',0,0,'','',-1);
INSERT INTO `block` VALUES (408,'menu','features','zen',0,0,'-1',0,0,'','',-1);
/*!40000 ALTER TABLE `block` ENABLE KEYS */;
UNLOCK TABLES;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

