
/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
DROP TABLE IF EXISTS `faq_expert`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `faq_expert` (
  `uid` int(10) unsigned NOT NULL COMMENT 'User identifier for the expert.',
  `tid` int(10) unsigned NOT NULL COMMENT 'Taxonomy identifier of the terms for the expert.',
  PRIMARY KEY (`uid`,`tid`),
  KEY `tid` (`tid`,`uid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='FAQ expert to term mapping.';
/*!40101 SET character_set_client = @saved_cs_client */;

LOCK TABLES `faq_expert` WRITE;
/*!40000 ALTER TABLE `faq_expert` DISABLE KEYS */;
INSERT INTO `faq_expert` VALUES (1,51);
INSERT INTO `faq_expert` VALUES (1,52);
INSERT INTO `faq_expert` VALUES (12,51);
INSERT INTO `faq_expert` VALUES (12,52);
INSERT INTO `faq_expert` VALUES (13,0);
INSERT INTO `faq_expert` VALUES (13,51);
INSERT INTO `faq_expert` VALUES (13,52);
INSERT INTO `faq_expert` VALUES (70,51);
INSERT INTO `faq_expert` VALUES (70,52);
/*!40000 ALTER TABLE `faq_expert` ENABLE KEYS */;
UNLOCK TABLES;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

