
/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
DROP TABLE IF EXISTS `search_node_links`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `search_node_links` (
  `sid` int(10) unsigned NOT NULL DEFAULT '0' COMMENT 'The search_dataset.sid of the searchable item containing the link to the node.',
  `type` varchar(16) NOT NULL DEFAULT '' COMMENT 'The search_dataset.type of the searchable item containing the link to the node.',
  `nid` int(10) unsigned NOT NULL DEFAULT '0' COMMENT 'The node.nid that this item links to.',
  `caption` longtext COMMENT 'The text used to link to the node.nid.',
  PRIMARY KEY (`sid`,`type`,`nid`),
  KEY `nid` (`nid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='Stores items (like nodes) that link to other nodes, used...';
/*!40101 SET character_set_client = @saved_cs_client */;

LOCK TABLES `search_node_links` WRITE;
/*!40000 ALTER TABLE `search_node_links` DISABLE KEYS */;
INSERT INTO `search_node_links` VALUES (73,'node',371,'lumina foundation');
INSERT INTO `search_node_links` VALUES (74,'node',90,'1 guiding evidencebased institutional change 2 influencing public policy 3 generating knowledge and 4 engaging the public');
INSERT INTO `search_node_links` VALUES (74,'node',285,'extensive network partners investors advisors coaches colleges and state policy teams');
INSERT INTO `search_node_links` VALUES (74,'node',371,'lumina foundation');
INSERT INTO `search_node_links` VALUES (90,'node',270,'generating knowledge');
INSERT INTO `search_node_links` VALUES (90,'node',271,'engaging the public');
INSERT INTO `search_node_links` VALUES (90,'node',276,'guiding evidencebased institutional change');
INSERT INTO `search_node_links` VALUES (91,'node',180,'read summary promising practices across all achieving the dream leader colleges');
INSERT INTO `search_node_links` VALUES (91,'node',192,'read achieving the dream president and ceo bill trueheart statement the interim evaluation');
INSERT INTO `search_node_links` VALUES (91,'node',268,'read about our state policy reform accomplishments');
INSERT INTO `search_node_links` VALUES (91,'node',299,'read the bulleted accomplishments our 2012 and 2011 leader colleges');
INSERT INTO `search_node_links` VALUES (91,'node',1669,'read the cutting edge series');
INSERT INTO `search_node_links` VALUES (92,'node',286,'join the achieving the dream network');
INSERT INTO `search_node_links` VALUES (92,'node',287,'attend one our events');
INSERT INTO `search_node_links` VALUES (92,'node',297,'work for achieving the dream');
INSERT INTO `search_node_links` VALUES (92,'node',2911,'become achieving the dream leader college');
INSERT INTO `search_node_links` VALUES (94,'node',90,'approaches');
INSERT INTO `search_node_links` VALUES (111,'node',109,'jobs for the future');
INSERT INTO `search_node_links` VALUES (111,'node',110,'institute for higher education leadership policy');
INSERT INTO `search_node_links` VALUES (111,'node',114,'time completion');
INSERT INTO `search_node_links` VALUES (112,'node',53,'achieving the dream');
INSERT INTO `search_node_links` VALUES (113,'node',53,'achieving the dream');
INSERT INTO `search_node_links` VALUES (115,'node',53,'achieving the dream');
INSERT INTO `search_node_links` VALUES (115,'node',116,'mdc');
INSERT INTO `search_node_links` VALUES (117,'node',53,'achieving the dream');
INSERT INTO `search_node_links` VALUES (118,'node',53,'achieving the dream');
INSERT INTO `search_node_links` VALUES (120,'node',53,'achieving the dream');
INSERT INTO `search_node_links` VALUES (120,'node',109,'jobs for the future');
INSERT INTO `search_node_links` VALUES (120,'node',119,'developmental education initiative');
INSERT INTO `search_node_links` VALUES (123,'node',53,'achieving the dream');
INSERT INTO `search_node_links` VALUES (123,'node',122,'public agenda');
INSERT INTO `search_node_links` VALUES (124,'node',53,'achieving the dream');
INSERT INTO `search_node_links` VALUES (125,'node',53,'achieving the dream');
INSERT INTO `search_node_links` VALUES (125,'node',109,'jobs for the future');
INSERT INTO `search_node_links` VALUES (126,'node',53,'achieving the dream');
INSERT INTO `search_node_links` VALUES (126,'node',122,'public agenda');
INSERT INTO `search_node_links` VALUES (129,'node',53,'achieving the dream');
INSERT INTO `search_node_links` VALUES (129,'node',122,'public agenda');
INSERT INTO `search_node_links` VALUES (131,'node',53,'achieving the dream');
INSERT INTO `search_node_links` VALUES (131,'node',109,'jobs for the future');
INSERT INTO `search_node_links` VALUES (132,'node',53,'achieving the dream');
INSERT INTO `search_node_links` VALUES (132,'node',109,'jobs for the future');
INSERT INTO `search_node_links` VALUES (133,'node',53,'achieving the dream');
INSERT INTO `search_node_links` VALUES (134,'node',53,'achieving the dream');
INSERT INTO `search_node_links` VALUES (135,'node',53,'achieving the dream');
INSERT INTO `search_node_links` VALUES (135,'node',109,'jobs for the future');
INSERT INTO `search_node_links` VALUES (137,'node',53,'achieving the dream');
INSERT INTO `search_node_links` VALUES (137,'node',109,'jobs for the future');
INSERT INTO `search_node_links` VALUES (139,'node',53,'achieving the dream');
INSERT INTO `search_node_links` VALUES (139,'node',109,'jobs for the future');
INSERT INTO `search_node_links` VALUES (140,'node',53,'achieving the dream');
INSERT INTO `search_node_links` VALUES (140,'node',122,'public agenda');
INSERT INTO `search_node_links` VALUES (141,'node',53,'achieving the dream');
INSERT INTO `search_node_links` VALUES (141,'node',109,'jobs for the future');
INSERT INTO `search_node_links` VALUES (142,'node',53,'achieving the dream');
INSERT INTO `search_node_links` VALUES (142,'node',127,'community college research center teachers college columbia university');
INSERT INTO `search_node_links` VALUES (142,'node',146,'mdrc');
INSERT INTO `search_node_links` VALUES (143,'node',53,'achieving the dream');
INSERT INTO `search_node_links` VALUES (143,'node',109,'jobs for the future');
INSERT INTO `search_node_links` VALUES (144,'node',53,'achieving the dream');
INSERT INTO `search_node_links` VALUES (144,'node',122,'public agenda');
INSERT INTO `search_node_links` VALUES (145,'node',53,'achieving the dream');
INSERT INTO `search_node_links` VALUES (145,'node',109,'jobs for the future');
INSERT INTO `search_node_links` VALUES (147,'node',53,'achieving the dream');
INSERT INTO `search_node_links` VALUES (147,'node',122,'public agenda');
INSERT INTO `search_node_links` VALUES (148,'node',53,'achieving the dream');
INSERT INTO `search_node_links` VALUES (148,'node',127,'community college research center teachers college columbia university');
INSERT INTO `search_node_links` VALUES (149,'node',146,'mdrc');
INSERT INTO `search_node_links` VALUES (150,'node',109,'jobs for the future');
INSERT INTO `search_node_links` VALUES (153,'node',146,'mdrc');
INSERT INTO `search_node_links` VALUES (154,'node',127,'community college research center teachers college columbia university');
INSERT INTO `search_node_links` VALUES (157,'node',53,'achieving the dream');
INSERT INTO `search_node_links` VALUES (158,'node',116,'mdc');
INSERT INTO `search_node_links` VALUES (159,'node',53,'achieving the dream');
INSERT INTO `search_node_links` VALUES (160,'node',53,'achieving the dream');
INSERT INTO `search_node_links` VALUES (164,'node',146,'mdrc');
INSERT INTO `search_node_links` VALUES (165,'node',127,'community college research center teachers college columbia university');
INSERT INTO `search_node_links` VALUES (167,'node',53,'achieving the dream');
INSERT INTO `search_node_links` VALUES (168,'node',53,'achieving the dream');
INSERT INTO `search_node_links` VALUES (169,'node',53,'achieving the dream');
INSERT INTO `search_node_links` VALUES (172,'node',53,'achieving the dream');
INSERT INTO `search_node_links` VALUES (173,'node',53,'achieving the dream');
INSERT INTO `search_node_links` VALUES (173,'node',146,'mdrc');
INSERT INTO `search_node_links` VALUES (178,'node',53,'achieving the dream');
INSERT INTO `search_node_links` VALUES (180,'node',181,'2011 promising practices');
INSERT INTO `search_node_links` VALUES (180,'node',212,'2010 promising practices');
INSERT INTO `search_node_links` VALUES (183,'node',53,'achieving the dream');
INSERT INTO `search_node_links` VALUES (183,'node',181,'2011 promising practices report full report');
INSERT INTO `search_node_links` VALUES (184,'node',53,'achieving the dream');
INSERT INTO `search_node_links` VALUES (184,'node',181,'2011 promising practices report full report');
INSERT INTO `search_node_links` VALUES (195,'node',53,'achieving the dream');
INSERT INTO `search_node_links` VALUES (195,'node',181,'2011 promising practices report full report');
INSERT INTO `search_node_links` VALUES (200,'node',53,'achieving the dream');
INSERT INTO `search_node_links` VALUES (200,'node',181,'2011 promising practices report full report');
INSERT INTO `search_node_links` VALUES (202,'node',53,'achieving the dream');
INSERT INTO `search_node_links` VALUES (202,'node',181,'2011 promising practices report full report');
INSERT INTO `search_node_links` VALUES (205,'node',53,'achieving the dream');
INSERT INTO `search_node_links` VALUES (205,'node',181,'2011 promising practices report full report');
INSERT INTO `search_node_links` VALUES (207,'node',53,'achieving the dream');
INSERT INTO `search_node_links` VALUES (207,'node',181,'2011 promising practices report full report');
INSERT INTO `search_node_links` VALUES (209,'node',53,'achieving the dream');
INSERT INTO `search_node_links` VALUES (209,'node',181,'2011 promising practices report full report');
INSERT INTO `search_node_links` VALUES (211,'node',53,'achieving the dream');
INSERT INTO `search_node_links` VALUES (211,'node',181,'2011 promising practices report full report');
INSERT INTO `search_node_links` VALUES (215,'node',53,'achieving the dream');
INSERT INTO `search_node_links` VALUES (215,'node',212,'2010 promising practices full report');
INSERT INTO `search_node_links` VALUES (217,'node',53,'achieving the dream');
INSERT INTO `search_node_links` VALUES (217,'node',212,'2010 promising practices full report');
INSERT INTO `search_node_links` VALUES (219,'node',53,'achieving the dream');
INSERT INTO `search_node_links` VALUES (219,'node',212,'2010 promising practices full report');
INSERT INTO `search_node_links` VALUES (220,'node',53,'achieving the dream');
INSERT INTO `search_node_links` VALUES (220,'node',212,'2010 promising practices full report');
INSERT INTO `search_node_links` VALUES (221,'node',53,'achieving the dream');
INSERT INTO `search_node_links` VALUES (221,'node',212,'2010 promising practices full report');
INSERT INTO `search_node_links` VALUES (222,'node',53,'achieving the dream');
INSERT INTO `search_node_links` VALUES (222,'node',212,'2010 promising practices full report');
INSERT INTO `search_node_links` VALUES (223,'node',53,'achieving the dream');
INSERT INTO `search_node_links` VALUES (223,'node',212,'2010 promising practices full report');
INSERT INTO `search_node_links` VALUES (224,'node',53,'achieving the dream');
INSERT INTO `search_node_links` VALUES (224,'node',212,'2010 promising practices full report');
INSERT INTO `search_node_links` VALUES (225,'node',212,'2010 promising practices full report');
INSERT INTO `search_node_links` VALUES (233,'node',53,'achieving the dream');
INSERT INTO `search_node_links` VALUES (233,'node',109,'jobs for the future');
INSERT INTO `search_node_links` VALUES (234,'node',125,'here');
INSERT INTO `search_node_links` VALUES (234,'node',233,'achieving the dream state policy framework');
INSERT INTO `search_node_links` VALUES (245,'node',111,'taking the next step the promise intermediate measure for meeting postsecondary completion goals');
INSERT INTO `search_node_links` VALUES (261,'node',53,'achieving the dream');
INSERT INTO `search_node_links` VALUES (261,'node',109,'jobs for the future');
INSERT INTO `search_node_links` VALUES (262,'node',53,'achieving the dream');
INSERT INTO `search_node_links` VALUES (262,'node',109,'jobs for the future');
INSERT INTO `search_node_links` VALUES (262,'node',119,'developmental education initiative');
INSERT INTO `search_node_links` VALUES (262,'node',263,'breaking through');
INSERT INTO `search_node_links` VALUES (264,'node',53,'achieving the dream');
INSERT INTO `search_node_links` VALUES (264,'node',109,'jobs for the future');
INSERT INTO `search_node_links` VALUES (264,'node',116,'mdc');
INSERT INTO `search_node_links` VALUES (264,'node',119,'developmental education initiative');
INSERT INTO `search_node_links` VALUES (264,'node',265,'btw informing change');
INSERT INTO `search_node_links` VALUES (266,'node',53,'achieving the dream');
INSERT INTO `search_node_links` VALUES (266,'node',109,'jobs for the future');
INSERT INTO `search_node_links` VALUES (266,'node',116,'mdc');
INSERT INTO `search_node_links` VALUES (266,'node',119,'developmental education initiative');
INSERT INTO `search_node_links` VALUES (267,'node',233,'state policy framework');
INSERT INTO `search_node_links` VALUES (267,'node',1566,'state policy selfassessment tool');
INSERT INTO `search_node_links` VALUES (273,'node',302,'michigan');
INSERT INTO `search_node_links` VALUES (273,'node',304,'arkansas');
INSERT INTO `search_node_links` VALUES (273,'node',305,'virginia');
INSERT INTO `search_node_links` VALUES (273,'node',306,'connecticut');
INSERT INTO `search_node_links` VALUES (273,'node',307,'florida');
INSERT INTO `search_node_links` VALUES (273,'node',308,'hawaii');
INSERT INTO `search_node_links` VALUES (273,'node',309,'indiana');
INSERT INTO `search_node_links` VALUES (273,'node',310,'massachusetts');
INSERT INTO `search_node_links` VALUES (273,'node',311,'north carolina');
INSERT INTO `search_node_links` VALUES (273,'node',312,'ohio');
INSERT INTO `search_node_links` VALUES (273,'node',313,'oklahoma');
INSERT INTO `search_node_links` VALUES (273,'node',314,'pennsylvania');
INSERT INTO `search_node_links` VALUES (273,'node',315,'south carolina');
INSERT INTO `search_node_links` VALUES (273,'node',316,'texas');
INSERT INTO `search_node_links` VALUES (273,'node',317,'washington');
INSERT INTO `search_node_links` VALUES (276,'node',97,'4 principles institutional improvement');
INSERT INTO `search_node_links` VALUES (276,'node',176,'1 goal');
INSERT INTO `search_node_links` VALUES (277,'node',90,'approaches');
INSERT INTO `search_node_links` VALUES (277,'node',109,'jobs for the future');
INSERT INTO `search_node_links` VALUES (277,'node',130,'see example');
INSERT INTO `search_node_links` VALUES (277,'node',267,'explore tools that all states can use');
INSERT INTO `search_node_links` VALUES (277,'node',273,'15 states meet the achieving the dream state policy teams');
INSERT INTO `search_node_links` VALUES (286,'node',276,'studentcentered model institutional improvement');
INSERT INTO `search_node_links` VALUES (286,'node',1483,'assistant director programs mia ramos');
INSERT INTO `search_node_links` VALUES (286,'node',3979,'view the rfp for the 2013 college cohort');
INSERT INTO `search_node_links` VALUES (287,'node',234,'learn more about achieving the dream state policy work');
INSERT INTO `search_node_links` VALUES (287,'node',276,'learn more about achieving the dream institutional change work');
INSERT INTO `search_node_links` VALUES (287,'node',1438,'view the photos from the 2011 strategy institute');
INSERT INTO `search_node_links` VALUES (287,'node',1630,'see what happened dream 2012');
INSERT INTO `search_node_links` VALUES (287,'node',2689,'kickoff 2012');
INSERT INTO `search_node_links` VALUES (287,'node',3531,'kickoff 2012 resources');
INSERT INTO `search_node_links` VALUES (287,'node',3869,'dream 2013');
INSERT INTO `search_node_links` VALUES (302,'node',277,'learn more about the postsecondary state policy network and the individual states involved');
INSERT INTO `search_node_links` VALUES (304,'node',277,'learn more about the postsecondary state policy network and the individual states involved');
INSERT INTO `search_node_links` VALUES (305,'node',277,'learn more about the postsecondary state policy network and the individual states involved');
INSERT INTO `search_node_links` VALUES (305,'node',565,'danville community college');
INSERT INTO `search_node_links` VALUES (305,'node',607,'mountain empire community college');
INSERT INTO `search_node_links` VALUES (305,'node',695,'paul camp community college');
INSERT INTO `search_node_links` VALUES (305,'node',696,'patrick henry community college');
INSERT INTO `search_node_links` VALUES (305,'node',697,'northern virginia community college');
INSERT INTO `search_node_links` VALUES (305,'node',709,'tidewater community college');
INSERT INTO `search_node_links` VALUES (306,'node',277,'learn more about the postsecondary state policy network and the individual states involved');
INSERT INTO `search_node_links` VALUES (306,'node',587,'housatonic community college');
INSERT INTO `search_node_links` VALUES (306,'node',617,'norwalk community college');
INSERT INTO `search_node_links` VALUES (306,'node',680,'capital community college');
INSERT INTO `search_node_links` VALUES (307,'node',277,'learn more about the postsecondary state policy network and the individual states involved');
INSERT INTO `search_node_links` VALUES (308,'node',730,'seven community colleges');
INSERT INTO `search_node_links` VALUES (310,'node',277,'learn more about the postsecondary state policy network and the individual states involved');
INSERT INTO `search_node_links` VALUES (310,'node',555,'bunker hill community college');
INSERT INTO `search_node_links` VALUES (310,'node',642,'roxbury community college');
INSERT INTO `search_node_links` VALUES (310,'node',652,'springfield technical community college');
INSERT INTO `search_node_links` VALUES (310,'node',694,'northern essex community college');
INSERT INTO `search_node_links` VALUES (311,'node',277,'learn more about the postsecondary state policy network and the individual states involved');
INSERT INTO `search_node_links` VALUES (312,'node',277,'learn more about the postsecondary state policy network and the individual states involved');
INSERT INTO `search_node_links` VALUES (313,'node',277,'learn more about the postsecondary state policy network and the individual states involved');
INSERT INTO `search_node_links` VALUES (313,'node',620,'oklahoma city community college');
INSERT INTO `search_node_links` VALUES (313,'node',641,'rose state community college');
INSERT INTO `search_node_links` VALUES (313,'node',664,'tulsa community college');
INSERT INTO `search_node_links` VALUES (316,'node',277,'learn more about the postsecondary state policy network and the individual states involved');
INSERT INTO `search_node_links` VALUES (733,'node',3335,'15 exemplar community colleges earn 100000 each walmart press for completion grants');
INSERT INTO `search_node_links` VALUES (821,'node',3917,'view training videos and other resources');
INSERT INTO `search_node_links` VALUES (912,'node',1677,'achieving the dream launches new website and welcomes new staff members');
INSERT INTO `search_node_links` VALUES (912,'node',1686,'student tweeters join influential policymakers national conference');
INSERT INTO `search_node_links` VALUES (912,'node',1712,'the walmart foundation launches partnership help more community college students achieve their dream');
INSERT INTO `search_node_links` VALUES (1131,'node',274,'data');
INSERT INTO `search_node_links` VALUES (1131,'node',275,'equity');
INSERT INTO `search_node_links` VALUES (1131,'node',819,'achieving the dream database');
INSERT INTO `search_node_links` VALUES (1131,'node',820,'research using the achieving the dream database');
INSERT INTO `search_node_links` VALUES (1131,'node',821,'data tools');
INSERT INTO `search_node_links` VALUES (1131,'node',844,'knowledge center');
INSERT INTO `search_node_links` VALUES (1131,'node',1669,'cuttingedge series');
INSERT INTO `search_node_links` VALUES (1131,'node',3596,'dreamfolio');
INSERT INTO `search_node_links` VALUES (1477,'node',1480,'two community college students win big inaugural dream big for college tshirt design contest');
INSERT INTO `search_node_links` VALUES (1500,'node',604,'achieving the dream leader college');
INSERT INTO `search_node_links` VALUES (1559,'node',1482,'here');
INSERT INTO `search_node_links` VALUES (1577,'node',52,'katie loovis');
INSERT INTO `search_node_links` VALUES (1578,'node',87,'lauren lewis');
INSERT INTO `search_node_links` VALUES (1579,'node',87,'lauren lewis');
INSERT INTO `search_node_links` VALUES (1630,'node',1668,'view online');
INSERT INTO `search_node_links` VALUES (1630,'node',1688,'presentation materials');
INSERT INTO `search_node_links` VALUES (1630,'node',1701,'dream big video competition');
INSERT INTO `search_node_links` VALUES (1630,'node',1720,'wednesday highlights');
INSERT INTO `search_node_links` VALUES (1630,'node',1721,'evaluation survey');
INSERT INTO `search_node_links` VALUES (1630,'node',1832,'tuesday highlights');
INSERT INTO `search_node_links` VALUES (1630,'node',1838,'thursday highlights');
INSERT INTO `search_node_links` VALUES (1630,'node',1839,'friday highlights');
INSERT INTO `search_node_links` VALUES (1633,'node',1668,'view online');
INSERT INTO `search_node_links` VALUES (1669,'node',121,'cutting edge series 1 engaging adjunct and fulltime faculty student success innovation read more about cutting edge series 1 engaging adjunct and fulltime faculty student success innovation');
INSERT INTO `search_node_links` VALUES (1669,'node',227,'cutting edge series 2 scaling community college interventions read more about cutting edge series 2 scaling community college interventions');
INSERT INTO `search_node_links` VALUES (1669,'node',1190,'cutting edge series 3 building institutional capacity for datainformed decision making read more about cutting edge series 3 building institutional capacity for datainformed decision making');
INSERT INTO `search_node_links` VALUES (1670,'node',1642,'ccrc assessment evidence series contextualization basic skills instruction read more about ccrc assessment evidence series contextualization basic skills instruction');
INSERT INTO `search_node_links` VALUES (1670,'node',1643,'ccrc assessment evidence series developmental acceleration read more about ccrc assessment evidence series developmental acceleration');
INSERT INTO `search_node_links` VALUES (1670,'node',1644,'ccrc assessment evidence series developmental assessment and placement read more about ccrc assessment evidence series developmental assessment and placement');
INSERT INTO `search_node_links` VALUES (1670,'node',1645,'ccrc assessment evidence series developmental mathematics pedagogy read more about ccrc assessment evidence series developmental mathematics pedagogy');
INSERT INTO `search_node_links` VALUES (1670,'node',1646,'ccrc assessment evidence series get with the program read more about ccrc assessment evidence series get with the program');
INSERT INTO `search_node_links` VALUES (1670,'node',1647,'ccrc assessment evidence series institutional and program structure read more about ccrc assessment evidence series institutional and program structure');
INSERT INTO `search_node_links` VALUES (1670,'node',1648,'ccrc assessment evidence series nonacademic support read more about ccrc assessment evidence series nonacademic support');
INSERT INTO `search_node_links` VALUES (1670,'node',1649,'ccrc assessment evidence series online learning read more about ccrc assessment evidence series online learning');
INSERT INTO `search_node_links` VALUES (1670,'node',1650,'ccrc assessment evidence series organizational improvement read more about ccrc assessment evidence series organizational improvement');
INSERT INTO `search_node_links` VALUES (1677,'node',73,'twominute animation video');
INSERT INTO `search_node_links` VALUES (1677,'node',91,'results');
INSERT INTO `search_node_links` VALUES (1677,'node',267,'selfassessment tool');
INSERT INTO `search_node_links` VALUES (1677,'node',273,'state policy teams');
INSERT INTO `search_node_links` VALUES (1677,'node',280,'nicole melander');
INSERT INTO `search_node_links` VALUES (1677,'node',290,'george cushman');
INSERT INTO `search_node_links` VALUES (1677,'node',545,'new profiles');
INSERT INTO `search_node_links` VALUES (1677,'node',844,'knowledge center');
INSERT INTO `search_node_links` VALUES (1677,'node',1145,'laurece summers');
INSERT INTO `search_node_links` VALUES (1677,'node',1147,'debbie werden');
INSERT INTO `search_node_links` VALUES (1677,'node',1481,'sarah hollister');
INSERT INTO `search_node_links` VALUES (1677,'node',1482,'rachel singer');
INSERT INTO `search_node_links` VALUES (1677,'node',1483,'mia gabrielle ramos');
INSERT INTO `search_node_links` VALUES (1677,'node',1484,'derrick browning');
INSERT INTO `search_node_links` VALUES (1679,'node',1706,'zane state college receives national award');
INSERT INTO `search_node_links` VALUES (1685,'node',295,'joaquin castro');
INSERT INTO `search_node_links` VALUES (1688,'node',1687,'oklahoma city community college presentation dream college prep mathematics teamwork action');
INSERT INTO `search_node_links` VALUES (1688,'node',1689,'spotlight session community program community college success for all');
INSERT INTO `search_node_links` VALUES (1688,'node',1690,'take week off improve your campus with zero week');
INSERT INTO `search_node_links` VALUES (1688,'node',1691,'the healthsciencelc advantage creating learning communities allied health fields');
INSERT INTO `search_node_links` VALUES (1688,'node',1692,'matter degrees promising practices for community college student success');
INSERT INTO `search_node_links` VALUES (1688,'node',1693,'decide design refine and embrace the first year experience course');
INSERT INTO `search_node_links` VALUES (1688,'node',1694,'helping all students succeed universal design for learning tcc');
INSERT INTO `search_node_links` VALUES (1688,'node',1695,'promising practices developmental mathematics and first year experience two virginia leader colleges');
INSERT INTO `search_node_links` VALUES (1688,'node',1696,'intervention statewide design');
INSERT INTO `search_node_links` VALUES (1688,'node',1698,'virginia other earthquake shaking virginia aligning and redesigning reduce the need for developmental education');
INSERT INTO `search_node_links` VALUES (1688,'node',1716,'you have multicampus institution breaking down silos create unified approach student success');
INSERT INTO `search_node_links` VALUES (1688,'node',1724,'committed leadership more than lip service how administrative leaders can support interventions from the ground');
INSERT INTO `search_node_links` VALUES (1688,'node',1725,'broad engagement student success across the state');
INSERT INTO `search_node_links` VALUES (1688,'node',1771,'first year experience strategies online student orientation that closes the gaps');
INSERT INTO `search_node_links` VALUES (1688,'node',1772,'achieving the dream for stem students building campus bridges for workforce readiness');
INSERT INTO `search_node_links` VALUES (1688,'node',1773,'data matters mapping skills');
INSERT INTO `search_node_links` VALUES (1688,'node',1774,'spotlight session attracting adult learners through expanded prior learning assessment');
INSERT INTO `search_node_links` VALUES (1688,'node',1775,'harnessing technology provide online academic advising for all students');
INSERT INTO `search_node_links` VALUES (1688,'node',1776,'premeeting workshop the carnegie statway and quantway pathways networked improvement communities solving the problems developmental math community colleges');
INSERT INTO `search_node_links` VALUES (1688,'node',1777,'engaging faculty using data increase student success');
INSERT INTO `search_node_links` VALUES (1688,'node',1778,'reinventing the wheel conceptual approach for teaching arithmetic prealgebra');
INSERT INTO `search_node_links` VALUES (1688,'node',1792,'tale two colleges communicating strategy and increasing alignment with balanced scorecard metrics');
INSERT INTO `search_node_links` VALUES (1688,'node',1795,'spotlight session applying the achieving the dream framework create meaningful institutional change zane state college');
INSERT INTO `search_node_links` VALUES (1688,'node',1796,'communities practice supporting faculty learning and engagement through organic decentralized professional development');
INSERT INTO `search_node_links` VALUES (1688,'node',1797,'inspirations surprising findings and what have learned from achieving the dream analyses');
INSERT INTO `search_node_links` VALUES (1688,'node',1798,'scaling ccbc going above and beyond with academic success course');
INSERT INTO `search_node_links` VALUES (1688,'node',1805,'key successes and challenges the change process findings from the round 3 washington colleges progress achieving the dream');
INSERT INTO `search_node_links` VALUES (1688,'node',1807,'montcalm community college engaging the campus sparking the college interest achieving the dream');
INSERT INTO `search_node_links` VALUES (1688,'node',1808,'how you design college success course that engages faculty and promotes fullscale implementation');
INSERT INTO `search_node_links` VALUES (1688,'node',1843,'creating roadmap for scaling acceleration developmental education');
INSERT INTO `search_node_links` VALUES (1688,'node',1844,'quickstart college changing the preenrollment paradigm for early success among highrisk students');
INSERT INTO `search_node_links` VALUES (1688,'node',1847,'student success survey infinitely integrating student input');
INSERT INTO `search_node_links` VALUES (1688,'node',1848,'recipe for student success examining the essential ingredients student success courses');
INSERT INTO `search_node_links` VALUES (1688,'node',1849,'make personal college completion');
INSERT INTO `search_node_links` VALUES (1688,'node',1857,'spotlight session going from more most bringing innovation scale for inclusion');
INSERT INTO `search_node_links` VALUES (1688,'node',1858,'spotlight session improving developmental education lessons from rigorous research');
INSERT INTO `search_node_links` VALUES (1688,'node',1880,'combining successful strategies create fully integrated learning community');
INSERT INTO `search_node_links` VALUES (1688,'node',1881,'transforming institutional cultures learning community environments that increase student success');
INSERT INTO `search_node_links` VALUES (1852,'node',1630,'dream 2012 home');
INSERT INTO `search_node_links` VALUES (1852,'node',1668,'conference agenda');
INSERT INTO `search_node_links` VALUES (1852,'node',1688,'presentation materials');
INSERT INTO `search_node_links` VALUES (1852,'node',1701,'dream big video competition');
INSERT INTO `search_node_links` VALUES (1852,'node',1720,'wednesday highlights');
INSERT INTO `search_node_links` VALUES (1852,'node',1721,'evaluation survey');
INSERT INTO `search_node_links` VALUES (1852,'node',1832,'tuesday highlights');
INSERT INTO `search_node_links` VALUES (1852,'node',1838,'thursday highlights');
INSERT INTO `search_node_links` VALUES (1852,'node',1839,'friday highlights');
INSERT INTO `search_node_links` VALUES (1918,'node',1712,'read the news release announcing this partnership');
INSERT INTO `search_node_links` VALUES (1955,'node',288,'robert templin');
INSERT INTO `search_node_links` VALUES (1955,'node',697,'northern virginia community college');
INSERT INTO `search_node_links` VALUES (1956,'node',1774,'here');
INSERT INTO `search_node_links` VALUES (1958,'node',3481,'catalyst fund');
INSERT INTO `search_node_links` VALUES (1958,'node',3558,'texas peer coaching');
INSERT INTO `search_node_links` VALUES (2689,'node',2709,'readiness assessment');
INSERT INTO `search_node_links` VALUES (2689,'node',3531,'kickoff institute resources page');
INSERT INTO `search_node_links` VALUES (2710,'node',1144,'jazmin lopez');
INSERT INTO `search_node_links` VALUES (2717,'node',544,'aiken technical college');
INSERT INTO `search_node_links` VALUES (2717,'node',548,'ashevillebuncombe technical community college');
INSERT INTO `search_node_links` VALUES (2717,'node',555,'bunker hill community college bunker hill community college');
INSERT INTO `search_node_links` VALUES (2717,'node',558,'clover park technical college clover park technical college');
INSERT INTO `search_node_links` VALUES (2717,'node',560,'community college beaver county');
INSERT INTO `search_node_links` VALUES (2717,'node',561,'community college the district columbia');
INSERT INTO `search_node_links` VALUES (2717,'node',562,'community college vermont');
INSERT INTO `search_node_links` VALUES (2717,'node',565,'danville community college');
INSERT INTO `search_node_links` VALUES (2717,'node',566,'davidson county community college');
INSERT INTO `search_node_links` VALUES (2717,'node',567,'delaware county community college');
INSERT INTO `search_node_links` VALUES (2717,'node',573,'edmonds community college');
INSERT INTO `search_node_links` VALUES (2717,'node',574,'centro college centro college');
INSERT INTO `search_node_links` VALUES (2717,'node',577,'everett community college');
INSERT INTO `search_node_links` VALUES (2717,'node',589,'jefferson community and technical college');
INSERT INTO `search_node_links` VALUES (2717,'node',591,'lane community college');
INSERT INTO `search_node_links` VALUES (2717,'node',604,'montgomery county community college');
INSERT INTO `search_node_links` VALUES (2717,'node',607,'mountain empire community college');
INSERT INTO `search_node_links` VALUES (2717,'node',614,'northampton community college');
INSERT INTO `search_node_links` VALUES (2717,'node',621,'orangeburgcalhoun technical college');
INSERT INTO `search_node_links` VALUES (2717,'node',638,'raritan valley community college');
INSERT INTO `search_node_links` VALUES (2717,'node',639,'renton technical college center');
INSERT INTO `search_node_links` VALUES (2717,'node',642,'roxbury community college');
INSERT INTO `search_node_links` VALUES (2717,'node',643,'louis community college');
INSERT INTO `search_node_links` VALUES (2717,'node',645,'south seattle community college');
INSERT INTO `search_node_links` VALUES (2717,'node',647,'skagit valley college');
INSERT INTO `search_node_links` VALUES (2717,'node',652,'springfield technical community college');
INSERT INTO `search_node_links` VALUES (2717,'node',659,'texarkana college texarkana college');
INSERT INTO `search_node_links` VALUES (2717,'node',673,'westmoreland county community college');
INSERT INTO `search_node_links` VALUES (2717,'node',678,'anne arundel community college');
INSERT INTO `search_node_links` VALUES (2717,'node',683,'community college allegheny county');
INSERT INTO `search_node_links` VALUES (2717,'node',685,'cuyahoga community college cuyahoga community college');
INSERT INTO `search_node_links` VALUES (2717,'node',686,'del mar college');
INSERT INTO `search_node_links` VALUES (2717,'node',689,'ivy tech community colleges');
INSERT INTO `search_node_links` VALUES (2717,'node',693,'macomb community college macomb community college');
INSERT INTO `search_node_links` VALUES (2717,'node',694,'northern essex community college');
INSERT INTO `search_node_links` VALUES (2717,'node',695,'paul camp community college');
INSERT INTO `search_node_links` VALUES (2717,'node',696,'patrick henry community college');
INSERT INTO `search_node_links` VALUES (2717,'node',697,'northern virginia community college');
INSERT INTO `search_node_links` VALUES (2717,'node',701,'big bend community college');
INSERT INTO `search_node_links` VALUES (2717,'node',705,'community college philadelphia');
INSERT INTO `search_node_links` VALUES (2717,'node',706,'laguardia community college');
INSERT INTO `search_node_links` VALUES (2717,'node',709,'tidewater community college');
INSERT INTO `search_node_links` VALUES (2862,'node',276,'here');
INSERT INTO `search_node_links` VALUES (2862,'node',940,'the kresge foundation');
INSERT INTO `search_node_links` VALUES (2862,'node',2616,'albany technical college');
INSERT INTO `search_node_links` VALUES (2862,'node',2617,'arkansas baptist college');
INSERT INTO `search_node_links` VALUES (2862,'node',2618,'atlanta technical college');
INSERT INTO `search_node_links` VALUES (2862,'node',2620,'central alabama community college');
INSERT INTO `search_node_links` VALUES (2862,'node',2621,'central georgia technical college');
INSERT INTO `search_node_links` VALUES (2862,'node',2622,'college southern nevada');
INSERT INTO `search_node_links` VALUES (2862,'node',2623,'columbus state community college');
INSERT INTO `search_node_links` VALUES (2862,'node',2624,'columbus technical college');
INSERT INTO `search_node_links` VALUES (2862,'node',2625,'gaston college');
INSERT INTO `search_node_links` VALUES (2862,'node',2626,'georgia piedmont technical college');
INSERT INTO `search_node_links` VALUES (2862,'node',2628,'stanly community college');
INSERT INTO `search_node_links` VALUES (2862,'node',2629,'wallace state community college hanceville');
INSERT INTO `search_node_links` VALUES (2862,'node',2630,'linnbenton community college');
INSERT INTO `search_node_links` VALUES (2862,'node',2631,'petersburg college');
INSERT INTO `search_node_links` VALUES (2862,'node',2632,'miami dade college');
INSERT INTO `search_node_links` VALUES (2862,'node',2634,'blue mountain community college');
INSERT INTO `search_node_links` VALUES (2862,'node',2635,'columbia gorge community college');
INSERT INTO `search_node_links` VALUES (2862,'node',2636,'klamath community college');
INSERT INTO `search_node_links` VALUES (2862,'node',2637,'oregon coast community college');
INSERT INTO `search_node_links` VALUES (2862,'node',2638,'southwestern oregon community college');
INSERT INTO `search_node_links` VALUES (2862,'node',2639,'tillamook bay community college');
INSERT INTO `search_node_links` VALUES (2862,'node',2641,'umpqua community college');
INSERT INTO `search_node_links` VALUES (2862,'node',2642,'kingsborough community college');
INSERT INTO `search_node_links` VALUES (2911,'node',97,'four principles');
INSERT INTO `search_node_links` VALUES (2911,'node',176,'measures student success');
INSERT INTO `search_node_links` VALUES (2911,'node',2912,'2012 leader college guidelines and application');
INSERT INTO `search_node_links` VALUES (2911,'node',3933,'here');
INSERT INTO `search_node_links` VALUES (2931,'node',281,'mark motamen');
INSERT INTO `search_node_links` VALUES (3185,'node',3183,'the official achieving the dream inc logo');
INSERT INTO `search_node_links` VALUES (3185,'node',3184,'the achieving the dream institution endorsement logo');
INSERT INTO `search_node_links` VALUES (3185,'node',3186,'the leader college mark distinction logo');
INSERT INTO `search_node_links` VALUES (3335,'node',544,'aiken technical college');
INSERT INTO `search_node_links` VALUES (3335,'node',545,'alamo colleges');
INSERT INTO `search_node_links` VALUES (3335,'node',553,'brazosport college');
INSERT INTO `search_node_links` VALUES (3335,'node',560,'community college beaver county');
INSERT INTO `search_node_links` VALUES (3335,'node',569,'durham technical community college');
INSERT INTO `search_node_links` VALUES (3335,'node',583,'guilford technical community college');
INSERT INTO `search_node_links` VALUES (3335,'node',614,'northampton community college');
INSERT INTO `search_node_links` VALUES (3335,'node',621,'orangeburgcalhoun technical college');
INSERT INTO `search_node_links` VALUES (3335,'node',637,'pulaski technical college');
INSERT INTO `search_node_links` VALUES (3335,'node',642,'roxbury community college');
INSERT INTO `search_node_links` VALUES (3335,'node',655,'tallahassee community college');
INSERT INTO `search_node_links` VALUES (3335,'node',668,'valencia college');
INSERT INTO `search_node_links` VALUES (3335,'node',676,'yakima valley community college');
INSERT INTO `search_node_links` VALUES (3335,'node',685,'cuyahoga community college');
INSERT INTO `search_node_links` VALUES (3335,'node',694,'northern essex community college');
INSERT INTO `search_node_links` VALUES (3351,'node',285,'atd national reform network');
INSERT INTO `search_node_links` VALUES (3351,'node',1712,'walmart press persistence retention and student success for completion');
INSERT INTO `search_node_links` VALUES (3359,'node',544,'aiken technical college');
INSERT INTO `search_node_links` VALUES (3359,'node',545,'alamo colleges');
INSERT INTO `search_node_links` VALUES (3359,'node',553,'brazosport college');
INSERT INTO `search_node_links` VALUES (3359,'node',560,'community college beaver county');
INSERT INTO `search_node_links` VALUES (3359,'node',569,'durham technical community college');
INSERT INTO `search_node_links` VALUES (3359,'node',583,'guilford technical community college');
INSERT INTO `search_node_links` VALUES (3359,'node',614,'northampton community college');
INSERT INTO `search_node_links` VALUES (3359,'node',621,'orangeburgcalhoun technical college');
INSERT INTO `search_node_links` VALUES (3359,'node',637,'pulaski technical college');
INSERT INTO `search_node_links` VALUES (3359,'node',642,'roxbury community college');
INSERT INTO `search_node_links` VALUES (3359,'node',655,'tallahassee community college');
INSERT INTO `search_node_links` VALUES (3359,'node',668,'valencia college');
INSERT INTO `search_node_links` VALUES (3359,'node',676,'yakima valley community college');
INSERT INTO `search_node_links` VALUES (3359,'node',685,'cuyahoga community college');
INSERT INTO `search_node_links` VALUES (3359,'node',694,'northern essex community college');
INSERT INTO `search_node_links` VALUES (3404,'node',544,'aiken technical college');
INSERT INTO `search_node_links` VALUES (3404,'node',545,'alamo colleges');
INSERT INTO `search_node_links` VALUES (3404,'node',553,'brazosport college');
INSERT INTO `search_node_links` VALUES (3404,'node',560,'community college beaver county');
INSERT INTO `search_node_links` VALUES (3404,'node',569,'durham technical community college');
INSERT INTO `search_node_links` VALUES (3404,'node',583,'guilford technical community college');
INSERT INTO `search_node_links` VALUES (3404,'node',614,'northampton community college');
INSERT INTO `search_node_links` VALUES (3404,'node',621,'orangeburgcalhoun technical college');
INSERT INTO `search_node_links` VALUES (3404,'node',637,'pulaski technical college');
INSERT INTO `search_node_links` VALUES (3404,'node',642,'roxbury community college');
INSERT INTO `search_node_links` VALUES (3404,'node',655,'tallahassee community college');
INSERT INTO `search_node_links` VALUES (3404,'node',668,'valencia college');
INSERT INTO `search_node_links` VALUES (3404,'node',676,'yakima valley community college');
INSERT INTO `search_node_links` VALUES (3404,'node',685,'cuyahoga community college');
INSERT INTO `search_node_links` VALUES (3404,'node',694,'northern essex community college');
INSERT INTO `search_node_links` VALUES (3481,'node',553,'brazosport college');
INSERT INTO `search_node_links` VALUES (3481,'node',555,'bunker hill community college');
INSERT INTO `search_node_links` VALUES (3481,'node',569,'durham technical community college');
INSERT INTO `search_node_links` VALUES (3481,'node',696,'patrick henry community college');
INSERT INTO `search_node_links` VALUES (3481,'node',3984,'read the news release announcing the grant recipients');
INSERT INTO `search_node_links` VALUES (3531,'node',121,'cutting edge series 1 engaging adjunct and fulltime faculty student success innovation');
INSERT INTO `search_node_links` VALUES (3531,'node',227,'cutting edge series 2 scaling community college interventions');
INSERT INTO `search_node_links` VALUES (3558,'node',97,'four principles');
INSERT INTO `search_node_links` VALUES (3558,'node',2911,'leader colleges');
INSERT INTO `search_node_links` VALUES (3594,'node',3520,'study from achieving the dream');
INSERT INTO `search_node_links` VALUES (3702,'node',553,'brazosport college');
INSERT INTO `search_node_links` VALUES (3702,'node',559,'college the ouachitas');
INSERT INTO `search_node_links` VALUES (3702,'node',679,'broward college');
INSERT INTO `search_node_links` VALUES (3702,'node',2642,'kingsborough community college');
INSERT INTO `search_node_links` VALUES (3760,'node',87,'lauren lewis');
INSERT INTO `search_node_links` VALUES (3760,'node',1480,'dream big for college tshirt contest');
INSERT INTO `search_node_links` VALUES (3760,'node',1779,'dream big for college video contest here');
INSERT INTO `search_node_links` VALUES (3760,'node',4080,'view the top 10 videos well additional stories from students who did not participate the official contest');
INSERT INTO `search_node_links` VALUES (3761,'node',3760,'dream big for college');
INSERT INTO `search_node_links` VALUES (3767,'node',2911,'leader colleges leader colleges');
INSERT INTO `search_node_links` VALUES (3784,'node',291,'leah meyer austin');
INSERT INTO `search_node_links` VALUES (3784,'node',3869,'dream 2013');
INSERT INTO `search_node_links` VALUES (3791,'node',691,'lake michigan college');
INSERT INTO `search_node_links` VALUES (3792,'node',612,'north central state college');
INSERT INTO `search_node_links` VALUES (3793,'node',614,'northampton community college');
INSERT INTO `search_node_links` VALUES (3794,'node',614,'northampton community college');
INSERT INTO `search_node_links` VALUES (3795,'node',560,'community college beaver county');
INSERT INTO `search_node_links` VALUES (3796,'node',560,'community college beaver county');
INSERT INTO `search_node_links` VALUES (3797,'node',571,'eastern gateway community college');
INSERT INTO `search_node_links` VALUES (3798,'node',578,'galveston college');
INSERT INTO `search_node_links` VALUES (3799,'node',645,'seattle central community college');
INSERT INTO `search_node_links` VALUES (3800,'node',649,'southwest texas junior college');
INSERT INTO `search_node_links` VALUES (3801,'node',586,'highline community college');
INSERT INTO `search_node_links` VALUES (3802,'node',593,'lee college');
INSERT INTO `search_node_links` VALUES (3803,'node',593,'lee college');
INSERT INTO `search_node_links` VALUES (3804,'node',593,'lee college');
INSERT INTO `search_node_links` VALUES (3805,'node',593,'lee college');
INSERT INTO `search_node_links` VALUES (3806,'node',648,'south texas college');
INSERT INTO `search_node_links` VALUES (3807,'node',648,'south texas college');
INSERT INTO `search_node_links` VALUES (3808,'node',684,'community college baltimore county');
INSERT INTO `search_node_links` VALUES (3809,'node',681,'coastal bend college');
INSERT INTO `search_node_links` VALUES (3810,'node',678,'anne arundel community college');
INSERT INTO `search_node_links` VALUES (3811,'node',678,'anne arundel community college');
INSERT INTO `search_node_links` VALUES (3812,'node',678,'anne arundel community college');
INSERT INTO `search_node_links` VALUES (3813,'node',693,'macomb community college');
INSERT INTO `search_node_links` VALUES (3814,'node',553,'brazosport college');
INSERT INTO `search_node_links` VALUES (3815,'node',618,'oakland community college');
INSERT INTO `search_node_links` VALUES (3816,'node',660,'texas southern university');
INSERT INTO `search_node_links` VALUES (3817,'node',548,'ashevillebuncombe technical community college');
INSERT INTO `search_node_links` VALUES (3818,'node',691,'lake michigan college');
INSERT INTO `search_node_links` VALUES (3819,'node',621,'orangeburgcalhoun technical college');
INSERT INTO `search_node_links` VALUES (3820,'node',677,'zane state college');
INSERT INTO `search_node_links` VALUES (3821,'node',609,'national park community college');
INSERT INTO `search_node_links` VALUES (3823,'node',612,'north central state college');
INSERT INTO `search_node_links` VALUES (3824,'node',612,'north central state college');
INSERT INTO `search_node_links` VALUES (3825,'node',680,'capital community college');
INSERT INTO `search_node_links` VALUES (3826,'node',614,'northampton community college');
INSERT INTO `search_node_links` VALUES (3827,'node',694,'northern essex community college');
INSERT INTO `search_node_links` VALUES (3828,'node',694,'northern essex community college');
INSERT INTO `search_node_links` VALUES (3829,'node',620,'oklahoma city community college');
INSERT INTO `search_node_links` VALUES (3830,'node',559,'college the ouachitas');
INSERT INTO `search_node_links` VALUES (3831,'node',685,'cuyahoga community college');
INSERT INTO `search_node_links` VALUES (3832,'node',571,'eastern gateway community college');
INSERT INTO `search_node_links` VALUES (3833,'node',578,'galveston college');
INSERT INTO `search_node_links` VALUES (3834,'node',645,'seattle central community college');
INSERT INTO `search_node_links` VALUES (3835,'node',645,'seattle central community college');
INSERT INTO `search_node_links` VALUES (3836,'node',649,'southwest texas junior college');
INSERT INTO `search_node_links` VALUES (3837,'node',586,'highline community college');
INSERT INTO `search_node_links` VALUES (3838,'node',654,'tacoma community college');
INSERT INTO `search_node_links` VALUES (3839,'node',654,'tacoma community college');
INSERT INTO `search_node_links` VALUES (3841,'node',668,'valencia college');
INSERT INTO `search_node_links` VALUES (3842,'node',673,'westmoreland county community college');
INSERT INTO `search_node_links` VALUES (3843,'node',676,'yakima valley community college');
INSERT INTO `search_node_links` VALUES (3844,'node',590,'kilgore college');
INSERT INTO `search_node_links` VALUES (3869,'node',3919,'reserve your spot today');
INSERT INTO `search_node_links` VALUES (3869,'node',3924,'exciting lineup 10 premeeting workshops');
INSERT INTO `search_node_links` VALUES (3869,'node',3962,'meet our 4 dreambassadors');
INSERT INTO `search_node_links` VALUES (3869,'node',4062,'the dream agenda');
INSERT INTO `search_node_links` VALUES (3869,'node',4082,'learn more');
INSERT INTO `search_node_links` VALUES (3871,'node',3919,'reserve your spot today');
INSERT INTO `search_node_links` VALUES (3871,'node',3924,'exciting lineup 10 premeeting workshops');
INSERT INTO `search_node_links` VALUES (3871,'node',3962,'meet our 4 dreambassadors');
INSERT INTO `search_node_links` VALUES (3871,'node',4062,'the dream agenda');
INSERT INTO `search_node_links` VALUES (3871,'node',4082,'learn more');
INSERT INTO `search_node_links` VALUES (3894,'node',821,'data tool');
INSERT INTO `search_node_links` VALUES (3894,'node',3350,'dream');
INSERT INTO `search_node_links` VALUES (3914,'node',1480,'two community college students win big inaugural dream big for college');
INSERT INTO `search_node_links` VALUES (3914,'node',1701,'dream big for college video competition');
INSERT INTO `search_node_links` VALUES (3914,'node',1839,'dream 2012 friday highlights');
INSERT INTO `search_node_links` VALUES (3933,'node',709,'tidewater community college');
INSERT INTO `search_node_links` VALUES (3933,'node',3100,'recommendations');
INSERT INTO `search_node_links` VALUES (3937,'node',662,'trident technical college');
INSERT INTO `search_node_links` VALUES (3959,'node',3869,'dream 2013 dream 2013 dream 2013');
INSERT INTO `search_node_links` VALUES (3975,'node',3977,'14 achieving the dream institutions earn leader college distinction');
INSERT INTO `search_node_links` VALUES (3977,'node',551,'bay noc community college');
INSERT INTO `search_node_links` VALUES (3977,'node',556,'central piedmont community college');
INSERT INTO `search_node_links` VALUES (3977,'node',559,'college the ouachitas');
INSERT INTO `search_node_links` VALUES (3977,'node',566,'davidson county community college');
INSERT INTO `search_node_links` VALUES (3977,'node',576,'elgin community college');
INSERT INTO `search_node_links` VALUES (3977,'node',582,'greenville technical college');
INSERT INTO `search_node_links` VALUES (3977,'node',609,'national park community college');
INSERT INTO `search_node_links` VALUES (3977,'node',652,'springfield technical community college');
INSERT INTO `search_node_links` VALUES (3977,'node',658,'temple college');
INSERT INTO `search_node_links` VALUES (3977,'node',659,'texarkana college');
INSERT INTO `search_node_links` VALUES (3977,'node',662,'trident technical college');
INSERT INTO `search_node_links` VALUES (3977,'node',684,'community college baltimore county');
INSERT INTO `search_node_links` VALUES (3977,'node',692,'lone star college system');
INSERT INTO `search_node_links` VALUES (3977,'node',730,'university hawai community colleges');
INSERT INTO `search_node_links` VALUES (3977,'node',2911,'click here');
INSERT INTO `search_node_links` VALUES (3984,'node',2911,'click here');
INSERT INTO `search_node_links` VALUES (3999,'node',97,'achieving the dream studentcentered model institutional improvement');
INSERT INTO `search_node_links` VALUES (3999,'node',2911,'wwwachievingthedreamorg getinvolved leadercolleges');
INSERT INTO `search_node_links` VALUES (4001,'node',97,'achieving the dream studentcentered model institutional improvement');
INSERT INTO `search_node_links` VALUES (4001,'node',2911,'2012 leader college wwwachievingthedreamorg getinvolved leadercolleges');
INSERT INTO `search_node_links` VALUES (4038,'node',277,'click here');
INSERT INTO `search_node_links` VALUES (4038,'node',305,'virginia');
INSERT INTO `search_node_links` VALUES (4038,'node',306,'connecticut');
INSERT INTO `search_node_links` VALUES (4038,'node',308,'hawai');
INSERT INTO `search_node_links` VALUES (4038,'node',310,'massachusetts');
INSERT INTO `search_node_links` VALUES (4038,'node',313,'oklahoma');
INSERT INTO `search_node_links` VALUES (4043,'node',2911,'wwwachievingthedreamorg getinvolved leadercolleges');
INSERT INTO `search_node_links` VALUES (4065,'node',3979,'2013 cohort request for proposals');
INSERT INTO `search_node_links` VALUES (4068,'node',4000,'national student completion movement');
/*!40000 ALTER TABLE `search_node_links` ENABLE KEYS */;
UNLOCK TABLES;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

