
/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
DROP TABLE IF EXISTS `sessions`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `sessions` (
  `uid` int(10) unsigned NOT NULL COMMENT 'The users.uid corresponding to a session, or 0 for anonymous user.',
  `sid` varchar(128) NOT NULL COMMENT 'A session ID. The value is generated by Drupal’s session handlers.',
  `ssid` varchar(128) NOT NULL DEFAULT '' COMMENT 'Secure session ID. The value is generated by Drupal’s session handlers.',
  `hostname` varchar(128) NOT NULL DEFAULT '' COMMENT 'The IP address that last used this session ID (sid).',
  `timestamp` int(11) NOT NULL DEFAULT '0' COMMENT 'The Unix timestamp when this session last requested a page. Old records are purged by PHP automatically.',
  `cache` int(11) NOT NULL DEFAULT '0' COMMENT 'The time of this user’s last post. This is used when the site has specified a minimum_cache_lifetime. See cache_get().',
  `session` longblob COMMENT 'The serialized contents of $_SESSION, an array of name/value pairs that persists across page requests by this session ID. Drupal loads $_SESSION from here at the start of each request and saves it at the end.',
  PRIMARY KEY (`sid`,`ssid`),
  KEY `timestamp` (`timestamp`),
  KEY `uid` (`uid`),
  KEY `ssid` (`ssid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='Drupal’s session handlers read and write into the...';
/*!40101 SET character_set_client = @saved_cs_client */;

LOCK TABLES `sessions` WRITE;
/*!40000 ALTER TABLE `sessions` DISABLE KEYS */;
INSERT INTO `sessions` VALUES (12,'0PmzPKMyMcYD80_i_A6qeSbXV7ONY_DFR7598Oyx0WQ','','96.231.17.24',1357261601,0,'');
INSERT INTO `sessions` VALUES (12,'Ekf7CKCZrCejtjr6BAVuXmh3mrdg2f3CcKvMMmkLHeE','','184.81.8.114',1357245420,0,'masquerading|s:2:\"86\";');
INSERT INTO `sessions` VALUES (1,'JPgbq3vPn2dpc8dD5sm-Sh5xoUtGOVm92hOPJr2o5_4','','216.164.61.222',1357316487,0,'cache_expiration|a:2:{s:11:\"cache_block\";i:1357316482;s:10:\"cache_page\";i:1357316482;}');
INSERT INTO `sessions` VALUES (13,'TuLNnFmPC7CuwblPuypJcSUXdwhroAh4uvBldY8cXnY','','184.81.8.114',1357316935,0,'node_overview_filter|a:2:{i:0;a:2:{i:0;s:6:\"status\";i:1;s:8:\"status-0\";}i:1;a:2:{i:0;s:4:\"type\";i:1;s:4:\"news\";}}cache_expiration|a:2:{s:11:\"cache_block\";i:1357316935;s:10:\"cache_page\";i:1357316935;}');
INSERT INTO `sessions` VALUES (12,'XYwQioZs2aqjYk4vCZxeOqQahmSGp8ohWQM-1xN-1xE','','184.81.8.114',1357309935,0,'');
INSERT INTO `sessions` VALUES (16,'_WyTCyRIZiDjAjHqCbhXMQzpXpxhVZK0qOjRZIL6cgA','','71.127.41.35',1357224266,0,'cache_expiration|a:2:{s:11:\"cache_block\";i:1357224266;s:10:\"cache_page\";i:1357224266;}');
/*!40000 ALTER TABLE `sessions` ENABLE KEYS */;
UNLOCK TABLES;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

